var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/modules/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__00mkxea._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0qd6pz_.js")
R.c("server/chunks/ssr/[root-of-the-server]__0qya27c._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0bd0tfh._.js")
R.c("server/chunks/ssr/src_app_layout_tsx_0e7l2q7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_modules_page_actions_0~oixil.js")
R.m(76849)
module.exports=R.m(76849).exports
