var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/github/disconnect/route.js")
R.c("server/chunks/[root-of-the-server]__0k~y-c2._.js")
R.c("server/chunks/[root-of-the-server]__0gbgxty._.js")
R.c("server/chunks/node_modules_next_124cnn1._.js")
R.c("server/chunks/[root-of-the-server]__0.6bt.6._.js")
R.c("server/chunks/[root-of-the-server]__0a7cvxw._.js")
R.c("server/chunks/node_modules_next_03e_drb._.js")
R.c("server/chunks/_next-internal_server_app_api_github_disconnect_route_actions_0cm9coj.js")
R.m(60723)
module.exports=R.m(60723).exports
