var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/github/callback/route.js")
R.c("server/chunks/[root-of-the-server]__13ds7-2._.js")
R.c("server/chunks/[root-of-the-server]__0gbgxty._.js")
R.c("server/chunks/node_modules_next_124cnn1._.js")
R.c("server/chunks/[root-of-the-server]__0a7cvxw._.js")
R.c("server/chunks/[root-of-the-server]__0.6bt.6._.js")
R.c("server/chunks/node_modules_next_03e_drb._.js")
R.c("server/chunks/_next-internal_server_app_api_github_callback_route_actions_0y_wg~t.js")
R.m(32295)
module.exports=R.m(32295).exports
