var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/auth/logout/route.js")
R.c("server/chunks/[root-of-the-server]__0b9~xji._.js")
R.c("server/chunks/node_modules_next_124cnn1._.js")
R.c("server/chunks/node_modules_jose_dist_webapi_jwt_sign_09zz_xa.js")
R.c("server/chunks/node_modules_next_0tb9qp2._.js")
R.c("server/chunks/[root-of-the-server]__0gg3i.l._.js")
R.c("server/chunks/[root-of-the-server]__0.6bt.6._.js")
R.c("server/chunks/node_modules_0.zf-pu._.js")
R.c("server/chunks/_next-internal_server_app_api_auth_logout_route_actions_0fm~3ij.js")
R.m(10942)
module.exports=R.m(10942).exports
