var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/auth/signin/route.js")
R.c("server/chunks/[root-of-the-server]__0ysk1p2._.js")
R.c("server/chunks/node_modules_next_0tb9qp2._.js")
R.c("server/chunks/node_modules_next_124cnn1._.js")
R.c("server/chunks/[root-of-the-server]__0.6bt.6._.js")
R.c("server/chunks/node_modules_0.zf-pu._.js")
R.c("server/chunks/[root-of-the-server]__0gg3i.l._.js")
R.c("server/chunks/_next-internal_server_app_api_auth_signin_route_actions_13bajux.js")
R.m(42689)
module.exports=R.m(42689).exports
