package forbidden_bypass

import (
	"fmt"
	"net/http"
	"net/http/httptest"
	"strings"
	"sync"
	"testing"

	stringsutil "github.com/projectdiscovery/utils/strings"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/vigolium/vigolium/pkg/httpmsg"
	"github.com/vigolium/vigolium/pkg/modules/modkit"
	"github.com/vigolium/vigolium/pkg/modules/modtest"
)

// seed403 builds a request to rawURL with a synthetic 403 baseline response
// attached — the module only attempts a bypass when the original status is
// 401/403.
func seed403(t *testing.T, rawURL string) *httpmsg.HttpRequestResponse {
	t.Helper()
	base := modtest.Request(t, rawURL)
	rawResp := "HTTP/1.1 403 Forbidden\r\nContent-Type: text/html\r\nContent-Length: 9\r\n\r\nForbidden"
	resp := httpmsg.NewHttpResponse([]byte(rawResp))
	return httpmsg.NewHttpRequestResponse(base.Request(), resp)
}

// seedEdgeBlock403 builds a request whose captured baseline is a CloudFront
// "Request blocked" edge 403 (Server: CloudFront) rather than an application 403 —
// modelling a WAF/CDN block, not an app access-control decision.
func seedEdgeBlock403(t *testing.T, rawURL string) *httpmsg.HttpRequestResponse {
	t.Helper()
	base := modtest.Request(t, rawURL)
	body := "<html><body><H1>403 ERROR</H1>Request blocked. Generated by cloudfront (CloudFront)</body></html>"
	rawResp := "HTTP/1.1 403 Forbidden\r\nServer: CloudFront\r\nContent-Type: text/html\r\n" +
		fmt.Sprintf("Content-Length: %d\r\n\r\n%s", len(body), body)
	resp := httpmsg.NewHttpResponse([]byte(rawResp))
	return httpmsg.NewHttpRequestResponse(base.Request(), resp)
}

// TestScanPerRequest_NoFalsePositive_CloudFrontEdgeBlockBaseline reproduces the
// WAF-block-baseline false positive: a CloudFront WAF rule blocks the literal
// protected path (/admin) with a "Request blocked" 403 captured as the baseline,
// while a path mutation that dodges the rule reaches the origin and returns 200.
// The bare-path re-fetch stays WAF-403, so the clean-canonical guard
// (stillForbiddenWithoutHeaders) is satisfied and a status-only check would report
// a bypass. An edge-blocked baseline is not an application access-control decision,
// so it must be discarded before any probing. Same server shape as
// TestScanPerRequest_DetectsPathBypass (which DOES report), the only difference
// being that the "forbidden" side is a vendor edge block.
func TestScanPerRequest_NoFalsePositive_CloudFrontEdgeBlockBaseline(t *testing.T) {
	t.Parallel()
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch {
		case r.URL.Path == "/admin":
			// CloudFront WAF deterministically blocks the literal path.
			w.Header().Set("Server", "CloudFront")
			w.WriteHeader(http.StatusForbidden)
			_, _ = w.Write([]byte("<html><body>Request blocked. Generated by cloudfront (CloudFront)</body></html>"))
		case strings.Contains(r.URL.Path, "admin"):
			w.WriteHeader(http.StatusOK)
			_, _ = w.Write([]byte("<html><body>SECRET ADMIN PANEL</body></html>"))
		default:
			w.WriteHeader(http.StatusNotFound)
		}
	}))
	defer srv.Close()

	client := modtest.Requester(t)
	rr := seedEdgeBlock403(t, srv.URL+"/admin")

	res, err := New().ScanPerRequest(rr, client, &modkit.ScanContext{})
	require.NoError(t, err)
	assert.Empty(t, res, "a CloudFront/WAF edge-block baseline must not be reported as a 403 bypass")
}

// TestScanPerRequest_DetectsPathBypass drives the real scan method against a
// server that genuinely forbids the CLEAN protected path (/admin → 403) while a
// path mutation (/admin/, /./admin, …) reaches the resource with 200, and an
// unrelated random path 404s. The clean path stays forbidden, the mutated 200 is
// distinguishable from the host's wildcard response, so it is reported as a
// genuine bypass.
func TestScanPerRequest_DetectsPathBypass(t *testing.T) {
	t.Parallel()
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		// The exact clean path stays forbidden; a mutated path that still
		// references the resource serves it; an unrelated path (the wildcard
		// probe) is a genuine 404.
		switch {
		case r.URL.Path == "/admin":
			w.WriteHeader(http.StatusForbidden)
			_, _ = w.Write([]byte("Forbidden"))
		case strings.Contains(r.URL.Path, "admin"):
			w.WriteHeader(http.StatusOK)
			_, _ = w.Write([]byte("<html><body>SECRET ADMIN PANEL</body></html>"))
		default:
			w.WriteHeader(http.StatusNotFound)
		}
	}))
	defer srv.Close()

	client := modtest.Requester(t)
	rr := seed403(t, srv.URL+"/admin")

	res, err := New().ScanPerRequest(rr, client, &modkit.ScanContext{})
	require.NoError(t, err)
	require.NotEmpty(t, res, "expected a path-bypass finding when a mutation reaches the protected resource")
}

// TestScanPerRequest_NoFalsePositive_TransientBaselineNowPublic reproduces the
// transient-baseline FP class: the crawl captured a 403 for /admin (a rate-limit
// / WAF / deploy blip), but at scan time the resource is genuinely public — the
// clean /admin and every path mutation return the same 200. A random path 404s,
// so the wildcard and catch-all guards pass. Only the clean-canonical control
// (the bare /admin is now 200) catches that no access-control boundary exists.
func TestScanPerRequest_NoFalsePositive_TransientBaselineNowPublic(t *testing.T) {
	t.Parallel()
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		// The resource (and any mutation of it) is now publicly 200; unrelated
		// paths 404.
		if strings.Contains(r.URL.Path, "admin") {
			w.WriteHeader(http.StatusOK)
			_, _ = w.Write([]byte("<html><body>SECRET ADMIN PANEL</body></html>"))
			return
		}
		w.WriteHeader(http.StatusNotFound)
	}))
	defer srv.Close()

	client := modtest.Requester(t)
	rr := seed403(t, srv.URL+"/admin")

	res, err := New().ScanPerRequest(rr, client, &modkit.ScanContext{})
	require.NoError(t, err)
	assert.Empty(t, res, "a resource that is publicly 200 on its clean path must not be reported as a 403 bypass")
}

// TestScanPerRequest_NoFalsePositive_Catchall reproduces the catch-all false
// positive: the host answers EVERY path — the seeded resource is 403, but every
// mutated payload AND the random wildcard probe return the same 200 SPA shell.
// A status-only check would report every mutation as a bypass; the wildcard
// guard must reject them all.
func TestScanPerRequest_NoFalsePositive_Catchall(t *testing.T) {
	t.Parallel()
	const shell = "<!doctype html><html><head><title>App</title></head><body><div id=root></div></body></html>"
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "text/html; charset=UTF-8")
		w.WriteHeader(http.StatusOK) // same 200 shell for every path
		_, _ = w.Write([]byte(shell))
	}))
	defer srv.Close()

	client := modtest.Requester(t)
	rr := seed403(t, srv.URL+"/admin")

	res, err := New().ScanPerRequest(rr, client, &modkit.ScanContext{})
	require.NoError(t, err)
	assert.Empty(t, res, "a 200 catch-all shell must not be reported as a 403 bypass")
}

// TestScanPerRequest_NoFalsePositive_EmptyBodyCatchall reproduces the
// bsr.netflix.net false positive: a Google-fronted edge that answers EVERY path
// (the seeded resource, every mutated payload, and a clean random probe) with a
// blank 200 (Content-Length: 0). The wildcard guard (ConfirmNotSoft404)
// misses this because WildcardEntry.IsWildcard requires a non-empty body, and the
// reproducibility gate passes because a blank 200 reproduces perfectly. The
// random-path catch-all guard, which treats two empty bodies as identical, must
// reject it.
func TestScanPerRequest_NoFalsePositive_EmptyBodyCatchall(t *testing.T) {
	t.Parallel()
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		// Blank 200 for every path — no body written.
		w.Header().Set("Content-Type", "text/html; charset=UTF-8")
		w.WriteHeader(http.StatusOK)
	}))
	defer srv.Close()

	client := modtest.Requester(t)
	rr := seed403(t, srv.URL+"/logout")

	res, err := New().ScanPerRequest(rr, client, &modkit.ScanContext{})
	require.NoError(t, err)
	assert.Empty(t, res, "an empty-body 200 catch-all must not be reported as a 403 bypass")
}

// TestScanPerRequest_NoFalsePositive_WhitespacePayloadRootCollapse reproduces the
// login-uat.example.com false positive. The protected resource
// (/ui-sfdc-javascript-impl/) is 403 and a random path 404s — NOT a catch-all — so
// the wildcard/catch-all guards all pass. The trap is the legacy whitespace payload
// "/ <path> /": its request line "GET / /ui-sfdc-javascript-impl/ / HTTP/1.1" is
// parsed (by our own builder AND the origin) only up to the first interior space,
// collapsing the wire request to "GET /". The server's legitimate homepage 200 was
// then misreported as a path bypass. With the whitespace payloads removed and the
// collapse guard in place, no probe fetches the root, so nothing is reported.
func TestScanPerRequest_NoFalsePositive_WhitespacePayloadRootCollapse(t *testing.T) {
	t.Parallel()
	const homepage = "<!doctype html><html><head><title>Example Portal</title></head>" +
		"<body><h1>Welcome</h1><script>var OneTrust={};</script></body></html>"
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch {
		case r.URL.Path == "/" || r.URL.Path == "":
			// Site root: a real, substantial homepage (not a soft-404).
			w.Header().Set("Content-Type", "text/html; charset=UTF-8")
			w.WriteHeader(http.StatusOK)
			_, _ = w.Write([]byte(homepage))
		case strings.Contains(r.URL.Path, "sfdc"):
			// The genuinely protected resource stays forbidden for every mutation.
			w.WriteHeader(http.StatusForbidden)
			_, _ = w.Write([]byte("Forbidden"))
		default:
			// Unrelated/random paths are a clean 404 — proving this host is NOT a
			// catch-all, so the existing catch-all guards cannot save us here.
			w.WriteHeader(http.StatusNotFound)
		}
	}))
	defer srv.Close()

	client := modtest.Requester(t)
	rr := seed403(t, srv.URL+"/ui-sfdc-javascript-impl/")

	res, err := New().ScanPerRequest(rr, client, &modkit.ScanContext{})
	require.NoError(t, err)
	assert.Empty(t, res, "a whitespace payload that collapses to the homepage must not be reported as a 403 bypass")
}

// pathHasManglingArtifact reports whether a raw request target carries a path
// normalization / traversal artifact — the shape a reverse proxy renders its
// generic soft page for. Used by the shape-catch-all regression handler below.
func pathHasManglingArtifact(rawURI string) bool {
	return stringsutil.ContainsAny(rawURI, "..", "//", ";", "%", `\`, "/.")
}

// TestScanPerRequest_NoFalsePositive_ShapeCatchall reproduces the reported
// dialog1.acme.com (Salesforce Lightning behind a reverse proxy) false positive:
// the protected resource (/admin) is a genuine 403 and a CLEAN random path 404s —
// NOT a catch-all — so ConfirmNotSoft404 and confirmDistinctFromCatchAll (which
// probe clean paths) all pass. The trap is that the proxy soft-serves ONE
// base-independent 200 page for ANY path carrying a normalization/traversal
// artifact (`/./admin`, `/admin..;/`, `//admin`), so every path payload "reaches"
// that generic page. Only the path-shape catch-all control — re-applying the same
// payload transformation to a random base and seeing the same body — recognises the
// 200 is generic to the mangled shape rather than a bypass of /admin.
func TestScanPerRequest_NoFalsePositive_ShapeCatchall(t *testing.T) {
	t.Parallel()
	// One base-independent generic page served for any mangled path shape.
	const softPage = "<!doctype html><html><head><title>Welcome</title></head><body>" +
		"<span class=\"error-msg-box\">This feature is not available in your country.</span></body></html>"
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch {
		case r.RequestURI == "/admin":
			// The clean protected path stays genuinely forbidden.
			w.WriteHeader(http.StatusForbidden)
			_, _ = w.Write([]byte("Forbidden"))
		case pathHasManglingArtifact(r.RequestURI):
			// Any mangled-shape path gets the same generic 200 soft page, regardless
			// of which base segment it decorates.
			w.Header().Set("Content-Type", "text/html; charset=UTF-8")
			w.WriteHeader(http.StatusOK)
			_, _ = w.Write([]byte(softPage))
		default:
			// Clean unknown paths (the wildcard / catch-all reference probes) 404 —
			// so the clean-path guards cannot see the shape catch-all.
			w.WriteHeader(http.StatusNotFound)
		}
	}))
	defer srv.Close()

	client := modtest.Requester(t)
	rr := seed403(t, srv.URL+"/admin")

	res, err := New().ScanPerRequest(rr, client, &modkit.ScanContext{})
	require.NoError(t, err)
	assert.Empty(t, res, "a base-independent generic 200 served only for the mangled path shape must not be reported as a 403 bypass")
}

// TestScanPerRequest_DetectsTrustedHeaderBypass drives the scan against a backend
// that 403s the protected resource unless the request carries a spoofed
// reverse-proxy identity header (X-Forwarded-User: admin), in which case it serves
// the resource. The bare request stays 403 (causality holds) and an unrelated path
// 404s (not a catch-all), so the per-header trusted-identity probe is reported.
func TestScanPerRequest_DetectsTrustedHeaderBypass(t *testing.T) {
	t.Parallel()
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if strings.Contains(r.URL.Path, "admin") {
			if r.Header.Get("X-Forwarded-User") == "admin" {
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("<html><body>SECRET ADMIN PANEL — welcome admin</body></html>"))
				return
			}
			w.WriteHeader(http.StatusForbidden)
			_, _ = w.Write([]byte("Forbidden"))
			return
		}
		w.WriteHeader(http.StatusNotFound)
	}))
	defer srv.Close()

	client := modtest.Requester(t)
	rr := seed403(t, srv.URL+"/admin")

	res, err := New().ScanPerRequest(rr, client, &modkit.ScanContext{})
	require.NoError(t, err)
	require.NotEmpty(t, res, "expected a trusted identity-header bypass finding")
	assert.Equal(t, "x-forwarded-user", res[0].FuzzingParameter, "the trusted-identity phase should attribute the single header")
	assert.Equal(t, "Trusted Identity Header Authentication Bypass", res[0].Info.Name)
}

// TestScanPerRequest_DetectsCombinedTrustedHeaderBypass covers a gateway that
// authorizes only when the FULL proxy identity set is present together (user +
// email + groups), as oauth2-proxy does. No single header unlocks the resource, so
// the per-header phase finds nothing and the combined all-headers-at-once probe is
// what trips the bypass.
func TestScanPerRequest_DetectsCombinedTrustedHeaderBypass(t *testing.T) {
	t.Parallel()
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if strings.Contains(r.URL.Path, "admin") {
			if r.Header.Get("X-Forwarded-User") == "admin" &&
				r.Header.Get("X-Forwarded-Email") == "admin" &&
				r.Header.Get("X-Forwarded-Groups") == "admin" {
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("<html><body>SECRET ADMIN PANEL — full identity</body></html>"))
				return
			}
			w.WriteHeader(http.StatusForbidden)
			_, _ = w.Write([]byte("Forbidden"))
			return
		}
		w.WriteHeader(http.StatusNotFound)
	}))
	defer srv.Close()

	client := modtest.Requester(t)
	rr := seed403(t, srv.URL+"/admin")

	res, err := New().ScanPerRequest(rr, client, &modkit.ScanContext{})
	require.NoError(t, err)
	require.NotEmpty(t, res, "expected a combined trusted identity-header bypass finding")
	assert.Equal(t, "trusted-identity-headers", res[0].FuzzingParameter, "no single header unlocks it; the combined probe should be credited")
}

// TestStillForbiddenWithoutHeaders exercises the causality layer in isolation (the
// generic IP-header phase has no such check, so it cannot be exercised cleanly
// through ScanPerRequest): a bare request that is STILL access-controlled keeps the
// finding, while one that is 200 even without the header — a resource that simply
// went public — drops it.
func TestStillForbiddenWithoutHeaders(t *testing.T) {
	t.Parallel()

	t.Run("still forbidden keeps the finding", func(t *testing.T) {
		srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
			w.WriteHeader(http.StatusForbidden)
			_, _ = w.Write([]byte("Forbidden"))
		}))
		defer srv.Close()
		client := modtest.Requester(t)
		rr := modtest.Request(t, srv.URL+"/admin")
		assert.True(t, stillForbiddenWithoutHeaders(client, rr.Service(), rr.Request().Raw()),
			"a bare request that is still 403 must not suppress the bypass")
	})

	t.Run("public resource drops the finding", func(t *testing.T) {
		srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
			w.WriteHeader(http.StatusOK)
			_, _ = w.Write([]byte("public content"))
		}))
		defer srv.Close()
		client := modtest.Requester(t)
		rr := modtest.Request(t, srv.URL+"/admin")
		assert.False(t, stillForbiddenWithoutHeaders(client, rr.Service(), rr.Request().Raw()),
			"a resource that is 200 even without the header is not header-attributable")
	})
}

// TestScanPerRequest_NoFalsePositive_TransientBypass reproduces a transient 200:
// the very first admin request succeeds (a flap / race / caching edge), but the
// reproducibility re-fetch returns 404. The bypass does not reproduce, so the
// strict reproducibility gate must drop it.
func TestScanPerRequest_NoFalsePositive_TransientBypass(t *testing.T) {
	t.Parallel()
	var mu sync.Mutex
	servedAdmin := false
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if strings.Contains(r.URL.Path, "admin") {
			mu.Lock()
			first := !servedAdmin
			servedAdmin = true
			mu.Unlock()
			if first {
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("<html><body>SECRET ADMIN PANEL</body></html>"))
				return
			}
		}
		w.WriteHeader(http.StatusNotFound)
	}))
	defer srv.Close()

	client := modtest.Requester(t)
	rr := seed403(t, srv.URL+"/admin")

	res, err := New().ScanPerRequest(rr, client, &modkit.ScanContext{})
	require.NoError(t, err)
	assert.Empty(t, res, "a one-shot transient 200 that does not reproduce must not be reported")
}
