var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/github/repos/route.js")
R.c("server/chunks/[root-of-the-server]__0ruz71m._.js")
R.c("server/chunks/[root-of-the-server]__0gbgxty._.js")
R.c("server/chunks/node_modules_next_124cnn1._.js")
R.c("server/chunks/[root-of-the-server]__0.6bt.6._.js")
R.c("server/chunks/[root-of-the-server]__0a7cvxw._.js")
R.c("server/chunks/node_modules_next_03e_drb._.js")
R.c("server/chunks/_next-internal_server_app_api_github_repos_route_actions_0.47nu_.js")
R.m(83846)
module.exports=R.m(83846).exports
