var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/database/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0vz~4~b._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_05gz1mc.js")
R.c("server/chunks/ssr/[root-of-the-server]__089d9~8._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0bd0tfh._.js")
R.c("server/chunks/ssr/src_app_layout_tsx_0e7l2q7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_database_page_actions_0e-3_n8.js")
R.m(50755)
module.exports=R.m(50755).exports
