// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/agentic-scan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agentic-scan">> = Specific
  const handler = {} as typeof import("../../src/app/agentic-scan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/billing">> = Specific
  const handler = {} as typeof import("../../src/app/billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/config/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/config">> = Specific
  const handler = {} as typeof import("../../src/app/config/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/database/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/database">> = Specific
  const handler = {} as typeof import("../../src/app/database/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/extensions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/extensions">> = Specific
  const handler = {} as typeof import("../../src/app/extensions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/findings/[[...id]]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/findings/[[...id]]">> = Specific
  const handler = {} as typeof import("../../src/app/findings/[[...id]]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/http-records/[[...id]]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/http-records/[[...id]]">> = Specific
  const handler = {} as typeof import("../../src/app/http-records/[[...id]]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ingest/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ingest">> = Specific
  const handler = {} as typeof import("../../src/app/ingest/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/modules/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modules">> = Specific
  const handler = {} as typeof import("../../src/app/modules/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/oast-interactions/[[...id]]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/oast-interactions/[[...id]]">> = Specific
  const handler = {} as typeof import("../../src/app/oast-interactions/[[...id]]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/projects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects">> = Specific
  const handler = {} as typeof import("../../src/app/projects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/scan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/scan">> = Specific
  const handler = {} as typeof import("../../src/app/scan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/scope/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/scope">> = Specific
  const handler = {} as typeof import("../../src/app/scope/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/select-project/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/select-project">> = Specific
  const handler = {} as typeof import("../../src/app/select-project/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/settings/[[...tab]]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/[[...tab]]">> = Specific
  const handler = {} as typeof import("../../src/app/settings/[[...tab]]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/source-repos/[[...id]]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/source-repos/[[...id]]">> = Specific
  const handler = {} as typeof import("../../src/app/source-repos/[[...id]]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/team/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/team">> = Specific
  const handler = {} as typeof import("../../src/app/team/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/unauthorized/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/unauthorized">> = Specific
  const handler = {} as typeof import("../../src/app/unauthorized/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/access-code/route.cloud.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/access-code">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/access-code/route.cloud.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/logout/route.cloud.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/logout/route.cloud.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/me/route.cloud.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/me">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/me/route.cloud.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/signin/route.cloud.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/signin">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/signin/route.cloud.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/billing/checkout/route.cloud.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/checkout">> = Specific
  const handler = {} as typeof import("../../src/app/api/billing/checkout/route.cloud.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/billing/credits/route.cloud.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/credits">> = Specific
  const handler = {} as typeof import("../../src/app/api/billing/credits/route.cloud.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/billing/history/route.cloud.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/history">> = Specific
  const handler = {} as typeof import("../../src/app/api/billing/history/route.cloud.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/billing/portal/route.cloud.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/portal">> = Specific
  const handler = {} as typeof import("../../src/app/api/billing/portal/route.cloud.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/billing/webhook/route.cloud.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/webhook">> = Specific
  const handler = {} as typeof import("../../src/app/api/billing/webhook/route.cloud.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/config-check/route.cloud.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/config-check">> = Specific
  const handler = {} as typeof import("../../src/app/api/config-check/route.cloud.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/github/callback/route.cloud.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/github/callback">> = Specific
  const handler = {} as typeof import("../../src/app/api/github/callback/route.cloud.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/github/clone-url/route.cloud.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/github/clone-url">> = Specific
  const handler = {} as typeof import("../../src/app/api/github/clone-url/route.cloud.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/github/disconnect/route.cloud.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/github/disconnect">> = Specific
  const handler = {} as typeof import("../../src/app/api/github/disconnect/route.cloud.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/github/install/route.cloud.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/github/install">> = Specific
  const handler = {} as typeof import("../../src/app/api/github/install/route.cloud.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/github/repos/route.cloud.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/github/repos">> = Specific
  const handler = {} as typeof import("../../src/app/api/github/repos/route.cloud.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/github/status/route.cloud.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/github/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/github/status/route.cloud.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/proxy/[...path]/route.cloud.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/proxy/[...path]">> = Specific
  const handler = {} as typeof import("../../src/app/api/proxy/[...path]/route.cloud.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/team/invite/route.cloud.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/team/invite">> = Specific
  const handler = {} as typeof import("../../src/app/api/team/invite/route.cloud.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/team/members/route.cloud.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/team/members">> = Specific
  const handler = {} as typeof import("../../src/app/api/team/members/route.cloud.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/callback/route.cloud.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/callback">> = Specific
  const handler = {} as typeof import("../../src/app/callback/route.cloud.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/showcases/[slug]/route.cloud.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/showcases/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/showcases/[slug]/route.cloud.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/showcases/route.cloud.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/showcases">> = Specific
  const handler = {} as typeof import("../../src/app/showcases/route.cloud.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
