// Code generated by scripts/gen_codex_types.py from codex_app_server_protocol.v2.schemas.json.
// DO NOT EDIT.

package codexsdk

import "encoding/json"

// AbsolutePathBuf: A path that is guaranteed to be absolute and normalized (though it is not guaranteed to be
type AbsolutePathBuf = string

type AgentPath = string

// ApprovalsReviewer: Configures who approval requests are routed to for review. Examples include sandbox escape
// Configures who approval requests are routed to for review. Examples include sandbox
// escapes, blocked network access, MCP approval prompts, and ARC escalations. Defaults to
// `user`. `guardian_subagent` uses a carefully prompted subagent to gather relevant context
// and apply a risk-based decision framework before approving or denying the request.
type ApprovalsReviewer = string

const (
	ApprovalsReviewerUser ApprovalsReviewer = "user"
	ApprovalsReviewerGuardian_subagent ApprovalsReviewer = "guardian_subagent"
)

type CollabAgentStatus = string

const (
	CollabAgentStatusPendingInit CollabAgentStatus = "pendingInit"
	CollabAgentStatusRunning CollabAgentStatus = "running"
	CollabAgentStatusInterrupted CollabAgentStatus = "interrupted"
	CollabAgentStatusCompleted CollabAgentStatus = "completed"
	CollabAgentStatusErrored CollabAgentStatus = "errored"
	CollabAgentStatusShutdown CollabAgentStatus = "shutdown"
	CollabAgentStatusNotFound CollabAgentStatus = "notFound"
)

type CollabAgentTool = string

const (
	CollabAgentToolSpawnAgent CollabAgentTool = "spawnAgent"
	CollabAgentToolSendInput CollabAgentTool = "sendInput"
	CollabAgentToolResumeAgent CollabAgentTool = "resumeAgent"
	CollabAgentToolWait CollabAgentTool = "wait"
	CollabAgentToolCloseAgent CollabAgentTool = "closeAgent"
)

type CollabAgentToolCallStatus = string

const (
	CollabAgentToolCallStatusInProgress CollabAgentToolCallStatus = "inProgress"
	CollabAgentToolCallStatusCompleted CollabAgentToolCallStatus = "completed"
	CollabAgentToolCallStatusFailed CollabAgentToolCallStatus = "failed"
)

type CommandExecutionSource = string

const (
	CommandExecutionSourceAgent CommandExecutionSource = "agent"
	CommandExecutionSourceUserShell CommandExecutionSource = "userShell"
	CommandExecutionSourceUnifiedExecStartup CommandExecutionSource = "unifiedExecStartup"
	CommandExecutionSourceUnifiedExecInteraction CommandExecutionSource = "unifiedExecInteraction"
)

type CommandExecutionStatus = string

const (
	CommandExecutionStatusInProgress CommandExecutionStatus = "inProgress"
	CommandExecutionStatusCompleted CommandExecutionStatus = "completed"
	CommandExecutionStatusFailed CommandExecutionStatus = "failed"
	CommandExecutionStatusDeclined CommandExecutionStatus = "declined"
)

type DynamicToolCallStatus = string

const (
	DynamicToolCallStatusInProgress DynamicToolCallStatus = "inProgress"
	DynamicToolCallStatusCompleted DynamicToolCallStatus = "completed"
	DynamicToolCallStatusFailed DynamicToolCallStatus = "failed"
)

type McpToolCallStatus = string

const (
	McpToolCallStatusInProgress McpToolCallStatus = "inProgress"
	McpToolCallStatusCompleted McpToolCallStatus = "completed"
	McpToolCallStatusFailed McpToolCallStatus = "failed"
)

type NetworkAccess = string

const (
	NetworkAccessRestricted NetworkAccess = "restricted"
	NetworkAccessEnabled NetworkAccess = "enabled"
)

type PatchApplyStatus = string

const (
	PatchApplyStatusInProgress PatchApplyStatus = "inProgress"
	PatchApplyStatusCompleted PatchApplyStatus = "completed"
	PatchApplyStatusFailed PatchApplyStatus = "failed"
	PatchApplyStatusDeclined PatchApplyStatus = "declined"
)

type Personality = string

const (
	PersonalityNone Personality = "none"
	PersonalityFriendly Personality = "friendly"
	PersonalityPragmatic Personality = "pragmatic"
)

// ReasoningEffort: See https://platform.openai.com/docs/guides/reasoning?api-mode=responses#get-started-with-
// See https://platform.openai.com/docs/guides/reasoning?api-mode=responses#get-started-with-
// reasoning
type ReasoningEffort = string

const (
	ReasoningEffortNone ReasoningEffort = "none"
	ReasoningEffortMinimal ReasoningEffort = "minimal"
	ReasoningEffortLow ReasoningEffort = "low"
	ReasoningEffortMedium ReasoningEffort = "medium"
	ReasoningEffortHigh ReasoningEffort = "high"
	ReasoningEffortXhigh ReasoningEffort = "xhigh"
)

type SandboxMode = string

const (
	SandboxModeRead_only SandboxMode = "read-only"
	SandboxModeWorkspace_write SandboxMode = "workspace-write"
	SandboxModeDanger_full_access SandboxMode = "danger-full-access"
)

type ServiceTier = string

const (
	ServiceTierFast ServiceTier = "fast"
	ServiceTierFlex ServiceTier = "flex"
)

type ThreadActiveFlag = string

const (
	ThreadActiveFlagWaitingOnApproval ThreadActiveFlag = "waitingOnApproval"
	ThreadActiveFlagWaitingOnUserInput ThreadActiveFlag = "waitingOnUserInput"
)

type ThreadId = string

type TurnStatus = string

const (
	TurnStatusCompleted TurnStatus = "completed"
	TurnStatusInterrupted TurnStatus = "interrupted"
	TurnStatusFailed TurnStatus = "failed"
	TurnStatusInProgress TurnStatus = "inProgress"
)

type AgentMessageDeltaNotification struct {
	Delta string `json:"delta"`
	ItemId string `json:"itemId"`
	ThreadId string `json:"threadId"`
	TurnId string `json:"turnId"`
}

// AskForApproval can be either a string (e.g. "on-failure") or a struct with
// a Granular field, depending on the codex version. We use json.RawMessage
// to accept both forms.
type AskForApproval = json.RawMessage

type ByteRange struct {
	End int64 `json:"end"`
	Start int64 `json:"start"`
}

type ClientInfo struct {
	Name string `json:"name"`
	Title *string `json:"title,omitempty"`
	Version string `json:"version"`
}

// This translation layer make sure that we expose codex error code in camel case.  When an
// upstream HTTP status is available (for example, from the Responses API or a provider), it
// is forwarded in `httpStatusCode` on the relevant `codexErrorInfo` variant.
type CodexErrorInfo struct {
	HttpConnectionFailed map[string]any `json:"httpConnectionFailed,omitempty"`
	ResponseStreamConnectionFailed map[string]any `json:"responseStreamConnectionFailed,omitempty"`
	ResponseStreamDisconnected map[string]any `json:"responseStreamDisconnected,omitempty"`
	ResponseTooManyFailedAttempts map[string]any `json:"responseTooManyFailedAttempts,omitempty"`
}

type CollabAgentState struct {
	Message *string `json:"message,omitempty"`
	Status string `json:"status"`
}

type CommandAction struct {
	Command string `json:"command"`
	Name *string `json:"name,omitempty"`
	Path *string `json:"path,omitempty"`
	Type string `json:"type"`
	Query *string `json:"query,omitempty"`
}

type CommandExecutionOutputDeltaNotification struct {
	Delta string `json:"delta"`
	ItemId string `json:"itemId"`
	ThreadId string `json:"threadId"`
	TurnId string `json:"turnId"`
}

type DynamicToolCallOutputContentItem struct {
	Text *string `json:"text,omitempty"`
	Type string `json:"type"`
	ImageUrl *string `json:"imageUrl,omitempty"`
}

type ErrorNotification struct {
	Error TurnError `json:"error"`
	ThreadId string `json:"threadId"`
	TurnId string `json:"turnId"`
	WillRetry bool `json:"willRetry"`
}

type FileChangeOutputDeltaNotification struct {
	Delta string `json:"delta"`
	ItemId string `json:"itemId"`
	ThreadId string `json:"threadId"`
	TurnId string `json:"turnId"`
}

type FileUpdateChange struct {
	Diff string `json:"diff"`
	Kind PatchChangeKind `json:"kind"`
	Path string `json:"path"`
}

type GitInfo struct {
	Branch *string `json:"branch,omitempty"`
	OriginUrl *string `json:"originUrl,omitempty"`
	Sha *string `json:"sha,omitempty"`
}

type HookPromptFragment struct {
	HookRunId string `json:"hookRunId"`
	Text string `json:"text"`
}

// Client-declared capabilities negotiated during initialize.
type InitializeCapabilities struct {
	// Opt into receiving experimental API methods and fields.
	ExperimentalApi *bool `json:"experimentalApi,omitempty"`
	// Exact notification method names that should be suppressed for this connection (f
	OptOutNotificationMethods []string `json:"optOutNotificationMethods,omitempty"`
}

type InitializeParams struct {
	Capabilities *InitializeCapabilities `json:"capabilities,omitempty"`
	ClientInfo ClientInfo `json:"clientInfo"`
}

// InitializeResponse is returned by the server after the initialize handshake.
// This type is not in the JSON Schema — it's defined by the SDK convention.
type InitializeResponse struct {
	ServerInfo     *ServerInfo `json:"serverInfo,omitempty"`
	UserAgent      *string     `json:"userAgent,omitempty"`
	PlatformFamily *string     `json:"platformFamily,omitempty"`
	PlatformOS     *string     `json:"platformOs,omitempty"`
}

type ServerInfo struct {
	Name    *string `json:"name,omitempty"`
	Version *string `json:"version,omitempty"`
}

type ItemCompletedNotification struct {
	Item ThreadItem `json:"item"`
	ThreadId string `json:"threadId"`
	TurnId string `json:"turnId"`
}

type ItemStartedNotification struct {
	Item ThreadItem `json:"item"`
	ThreadId string `json:"threadId"`
	TurnId string `json:"turnId"`
}

type McpToolCallError struct {
	Message string `json:"message"`
}

type McpToolCallResult struct {
	Content []any `json:"content"`
	StructuredContent any `json:"structuredContent,omitempty"`
}

type MemoryCitation struct {
	Entries []MemoryCitationEntry `json:"entries"`
	ThreadIds []string `json:"threadIds"`
}

type MemoryCitationEntry struct {
	LineEnd int64 `json:"lineEnd"`
	LineStart int64 `json:"lineStart"`
	Note string `json:"note"`
	Path string `json:"path"`
}

// Classifies an assistant message as interim commentary or final answer text.  Providers do
// not emit this consistently, so callers must treat `None` as "phase unknown" and keep
// compatibility behavior for legacy models.
type MessagePhase struct {
}

type PatchChangeKind struct {
	Type string `json:"type"`
	Move_path *string `json:"move_path,omitempty"`
}

type ReadOnlyAccess struct {
	IncludePlatformDefaults *bool `json:"includePlatformDefaults,omitempty"`
	ReadableRoots []string `json:"readableRoots,omitempty"`
	Type string `json:"type"`
}

// A summary of the reasoning performed by the model. This can be useful for debugging and
// understanding the model's reasoning process. See
// https://platform.openai.com/docs/guides/reasoning?api-mode=responses#reasoning-summaries
type ReasoningSummary struct {
}

type ReasoningTextDeltaNotification struct {
	ContentIndex int64 `json:"contentIndex"`
	Delta string `json:"delta"`
	ItemId string `json:"itemId"`
	ThreadId string `json:"threadId"`
	TurnId string `json:"turnId"`
}

type SandboxPolicy struct {
	Type string `json:"type"`
	Access *ReadOnlyAccess `json:"access,omitempty"`
	NetworkAccess *bool `json:"networkAccess,omitempty"`
	ExcludeSlashTmp *bool `json:"excludeSlashTmp,omitempty"`
	ExcludeTmpdirEnvVar *bool `json:"excludeTmpdirEnvVar,omitempty"`
	ReadOnlyAccess *ReadOnlyAccess `json:"readOnlyAccess,omitempty"`
	WritableRoots []string `json:"writableRoots,omitempty"`
}

// SessionSource can be either a string (e.g. "app-server") or a struct with
// Custom/SubAgent fields, depending on the codex version. We use json.RawMessage
// to accept both forms.
type SessionSource = json.RawMessage

type SubAgentSource struct {
	Thread_spawn map[string]any `json:"thread_spawn,omitempty"`
	Other *string `json:"other,omitempty"`
}

type TextElement struct {
	// Byte range in the parent `text` buffer that this element occupies.
	ByteRange ByteRange `json:"byteRange"`
	// Optional human-readable placeholder for the element, displayed in the UI.
	Placeholder *string `json:"placeholder,omitempty"`
}

type Thread struct {
	// Optional random unique nickname assigned to an AgentControl-spawned sub-agent.
	AgentNickname *string `json:"agentNickname,omitempty"`
	// Optional role (agent_role) assigned to an AgentControl-spawned sub-agent.
	AgentRole *string `json:"agentRole,omitempty"`
	// Version of the CLI that created the thread.
	CliVersion string `json:"cliVersion"`
	// Unix timestamp (in seconds) when the thread was created.
	CreatedAt int64 `json:"createdAt"`
	// Working directory captured for the thread.
	Cwd string `json:"cwd"`
	// Whether the thread is ephemeral and should not be materialized on disk.
	Ephemeral bool `json:"ephemeral"`
	// Optional Git metadata captured when the thread was created.
	GitInfo *GitInfo `json:"gitInfo,omitempty"`
	Id string `json:"id"`
	// Model provider used for this thread (for example, 'openai').
	ModelProvider string `json:"modelProvider"`
	// Optional user-facing thread title.
	Name *string `json:"name,omitempty"`
	// [UNSTABLE] Path to the thread on disk.
	Path *string `json:"path,omitempty"`
	// Usually the first user message in the thread, if available.
	Preview string `json:"preview"`
	// Origin of the thread (CLI, VSCode, codex exec, codex app-server, etc.).
	Source SessionSource `json:"source"`
	// Current runtime status for the thread.
	Status ThreadStatus `json:"status"`
	// Only populated on `thread/resume`, `thread/rollback`, `thread/fork`, and `thread
	Turns []Turn `json:"turns"`
	// Unix timestamp (in seconds) when the thread was last updated.
	UpdatedAt int64 `json:"updatedAt"`
}

// There are two ways to fork a thread: 1. By thread_id: load the thread from disk by
// thread_id and fork it into a new thread. 2. By path: load the thread from disk by path and
// fork it into a new thread.  If using path, the thread_id param will be ignored.  Prefer
// using thread_id whenever possible.
type ThreadForkParams struct {
	ApprovalPolicy *AskForApproval `json:"approvalPolicy,omitempty"`
	// Override where approval requests are routed for review on this thread and subseq
	ApprovalsReviewer *string `json:"approvalsReviewer,omitempty"`
	BaseInstructions *string `json:"baseInstructions,omitempty"`
	Config *map[string]any `json:"config,omitempty"`
	Cwd *string `json:"cwd,omitempty"`
	DeveloperInstructions *string `json:"developerInstructions,omitempty"`
	Ephemeral *bool `json:"ephemeral,omitempty"`
	// Configuration overrides for the forked thread, if any.
	Model *string `json:"model,omitempty"`
	ModelProvider *string `json:"modelProvider,omitempty"`
	Sandbox *string `json:"sandbox,omitempty"`
	ServiceTier *string `json:"serviceTier,omitempty"`
	ThreadId string `json:"threadId"`
}

type ThreadForkResponse struct {
	ApprovalPolicy AskForApproval `json:"approvalPolicy"`
	// Reviewer currently used for approval requests on this thread.
	ApprovalsReviewer string `json:"approvalsReviewer"`
	Cwd string `json:"cwd"`
	Model string `json:"model"`
	ModelProvider string `json:"modelProvider"`
	ReasoningEffort *string `json:"reasoningEffort,omitempty"`
	Sandbox SandboxPolicy `json:"sandbox"`
	ServiceTier *string `json:"serviceTier,omitempty"`
	Thread Thread `json:"thread"`
}

type ThreadItem struct {
	Content []UserInput `json:"content,omitempty"`
	Id string `json:"id"`
	Type string `json:"type"`
	Fragments []HookPromptFragment `json:"fragments,omitempty"`
	MemoryCitation *MemoryCitation `json:"memoryCitation,omitempty"`
	Phase *MessagePhase `json:"phase,omitempty"`
	Text *string `json:"text,omitempty"`
	Summary []string `json:"summary,omitempty"`
	AggregatedOutput *string `json:"aggregatedOutput,omitempty"`
	Command *string `json:"command,omitempty"`
	CommandActions []CommandAction `json:"commandActions,omitempty"`
	Cwd *string `json:"cwd,omitempty"`
	DurationMs *int64 `json:"durationMs,omitempty"`
	ExitCode *int64 `json:"exitCode,omitempty"`
	ProcessId *string `json:"processId,omitempty"`
	Source *string `json:"source,omitempty"`
	Status *string `json:"status,omitempty"`
	Changes []FileUpdateChange `json:"changes,omitempty"`
	Arguments any `json:"arguments,omitempty"`
	Error *McpToolCallError `json:"error,omitempty"`
	Result *McpToolCallResult `json:"result,omitempty"`
	Server *string `json:"server,omitempty"`
	Tool *string `json:"tool,omitempty"`
	ContentItems []DynamicToolCallOutputContentItem `json:"contentItems,omitempty"`
	Success *bool `json:"success,omitempty"`
	AgentsStates map[string]any `json:"agentsStates,omitempty"`
	Model *string `json:"model,omitempty"`
	Prompt *string `json:"prompt,omitempty"`
	ReasoningEffort *string `json:"reasoningEffort,omitempty"`
	ReceiverThreadIds []string `json:"receiverThreadIds,omitempty"`
	SenderThreadId *string `json:"senderThreadId,omitempty"`
	Action *WebSearchAction `json:"action,omitempty"`
	Query *string `json:"query,omitempty"`
	Path *string `json:"path,omitempty"`
	RevisedPrompt *string `json:"revisedPrompt,omitempty"`
	SavedPath *string `json:"savedPath,omitempty"`
	Review *string `json:"review,omitempty"`
}

// There are three ways to resume a thread: 1. By thread_id: load the thread from disk by
// thread_id and resume it. 2. By history: instantiate the thread from memory and resume it.
// 3. By path: load the thread from disk by path and resume it.  The precedence is: history >
// path > thread_id. If using history or path, the thread_id param will be ignored.  Prefer
// using thread_id whenever possible.
type ThreadResumeParams struct {
	ApprovalPolicy *AskForApproval `json:"approvalPolicy,omitempty"`
	// Override where approval requests are routed for review on this thread and subseq
	ApprovalsReviewer *string `json:"approvalsReviewer,omitempty"`
	BaseInstructions *string `json:"baseInstructions,omitempty"`
	Config *map[string]any `json:"config,omitempty"`
	Cwd *string `json:"cwd,omitempty"`
	DeveloperInstructions *string `json:"developerInstructions,omitempty"`
	// Configuration overrides for the resumed thread, if any.
	Model *string `json:"model,omitempty"`
	ModelProvider *string `json:"modelProvider,omitempty"`
	Personality *string `json:"personality,omitempty"`
	Sandbox *string `json:"sandbox,omitempty"`
	ServiceTier *string `json:"serviceTier,omitempty"`
	ThreadId string `json:"threadId"`
}

type ThreadResumeResponse struct {
	ApprovalPolicy AskForApproval `json:"approvalPolicy"`
	// Reviewer currently used for approval requests on this thread.
	ApprovalsReviewer string `json:"approvalsReviewer"`
	Cwd string `json:"cwd"`
	Model string `json:"model"`
	ModelProvider string `json:"modelProvider"`
	ReasoningEffort *string `json:"reasoningEffort,omitempty"`
	Sandbox SandboxPolicy `json:"sandbox"`
	ServiceTier *string `json:"serviceTier,omitempty"`
	Thread Thread `json:"thread"`
}

type ThreadStartParams struct {
	ApprovalPolicy *AskForApproval `json:"approvalPolicy,omitempty"`
	// Override where approval requests are routed for review on this thread and subseq
	ApprovalsReviewer *string `json:"approvalsReviewer,omitempty"`
	BaseInstructions *string `json:"baseInstructions,omitempty"`
	Config *map[string]any `json:"config,omitempty"`
	Cwd *string `json:"cwd,omitempty"`
	DeveloperInstructions *string `json:"developerInstructions,omitempty"`
	Ephemeral *bool `json:"ephemeral,omitempty"`
	Model *string `json:"model,omitempty"`
	ModelProvider *string `json:"modelProvider,omitempty"`
	Personality *string `json:"personality,omitempty"`
	Sandbox *string `json:"sandbox,omitempty"`
	ServiceName *string `json:"serviceName,omitempty"`
	ServiceTier *string `json:"serviceTier,omitempty"`
}

type ThreadStartResponse struct {
	ApprovalPolicy AskForApproval `json:"approvalPolicy"`
	// Reviewer currently used for approval requests on this thread.
	ApprovalsReviewer string `json:"approvalsReviewer"`
	Cwd string `json:"cwd"`
	Model string `json:"model"`
	ModelProvider string `json:"modelProvider"`
	ReasoningEffort *string `json:"reasoningEffort,omitempty"`
	Sandbox SandboxPolicy `json:"sandbox"`
	ServiceTier *string `json:"serviceTier,omitempty"`
	Thread Thread `json:"thread"`
}

type ThreadStartedNotification struct {
	Thread Thread `json:"thread"`
}

type ThreadStatus struct {
	Type string `json:"type"`
	ActiveFlags []string `json:"activeFlags,omitempty"`
}

type ThreadTokenUsage struct {
	Last TokenUsageBreakdown `json:"last"`
	ModelContextWindow *int64 `json:"modelContextWindow,omitempty"`
	Total TokenUsageBreakdown `json:"total"`
}

type ThreadTokenUsageUpdatedNotification struct {
	ThreadId string `json:"threadId"`
	TokenUsage ThreadTokenUsage `json:"tokenUsage"`
	TurnId string `json:"turnId"`
}

type TokenUsageBreakdown struct {
	CachedInputTokens int64 `json:"cachedInputTokens"`
	InputTokens int64 `json:"inputTokens"`
	OutputTokens int64 `json:"outputTokens"`
	ReasoningOutputTokens int64 `json:"reasoningOutputTokens"`
	TotalTokens int64 `json:"totalTokens"`
}

type Turn struct {
	// Only populated when the Turn's status is failed.
	Error *TurnError `json:"error,omitempty"`
	Id string `json:"id"`
	// Only populated on a `thread/resume` or `thread/fork` response. For all other res
	Items []ThreadItem `json:"items"`
	Status string `json:"status"`
}

type TurnCompletedNotification struct {
	ThreadId string `json:"threadId"`
	Turn Turn `json:"turn"`
}

type TurnError struct {
	AdditionalDetails *string `json:"additionalDetails,omitempty"`
	CodexErrorInfo *CodexErrorInfo `json:"codexErrorInfo,omitempty"`
	Message string `json:"message"`
}

type TurnInterruptParams struct {
	ThreadId string `json:"threadId"`
	TurnId string `json:"turnId"`
}

type TurnInterruptResponse = map[string]any

type TurnStartParams struct {
	// Override the approval policy for this turn and subsequent turns.
	ApprovalPolicy *AskForApproval `json:"approvalPolicy,omitempty"`
	// Override where approval requests are routed for review on this turn and subseque
	ApprovalsReviewer *string `json:"approvalsReviewer,omitempty"`
	// Override the working directory for this turn and subsequent turns.
	Cwd *string `json:"cwd,omitempty"`
	// Override the reasoning effort for this turn and subsequent turns.
	Effort *string `json:"effort,omitempty"`
	Input []UserInput `json:"input"`
	// Override the model for this turn and subsequent turns.
	Model *string `json:"model,omitempty"`
	// Optional JSON Schema used to constrain the final assistant message for this turn
	OutputSchema any `json:"outputSchema,omitempty"`
	// Override the personality for this turn and subsequent turns.
	Personality *string `json:"personality,omitempty"`
	// Override the sandbox policy for this turn and subsequent turns.
	SandboxPolicy *SandboxPolicy `json:"sandboxPolicy,omitempty"`
	// Override the service tier for this turn and subsequent turns.
	ServiceTier *string `json:"serviceTier,omitempty"`
	// Override the reasoning summary for this turn and subsequent turns.
	Summary *ReasoningSummary `json:"summary,omitempty"`
	ThreadId string `json:"threadId"`
}

type TurnStartResponse struct {
	Turn Turn `json:"turn"`
}

type TurnStartedNotification struct {
	ThreadId string `json:"threadId"`
	Turn Turn `json:"turn"`
}

type TurnSteerParams struct {
	// Required active turn id precondition. The request fails when it does not match t
	ExpectedTurnId string `json:"expectedTurnId"`
	Input []UserInput `json:"input"`
	ThreadId string `json:"threadId"`
}

type TurnSteerResponse struct {
	TurnId string `json:"turnId"`
}

type UserInput struct {
	Text *string `json:"text,omitempty"`
	Text_elements []TextElement `json:"text_elements,omitempty"`
	Type string `json:"type"`
	Url *string `json:"url,omitempty"`
	Path *string `json:"path,omitempty"`
	Name *string `json:"name,omitempty"`
}

type WebSearchAction struct {
	Queries []string `json:"queries,omitempty"`
	Query *string `json:"query,omitempty"`
	Type string `json:"type"`
	Url *string `json:"url,omitempty"`
	Pattern *string `json:"pattern,omitempty"`
}

