package secretscan

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"sync"

	"github.com/vigolium/vigolium/pkg/secretscan/catalog"
)

// catalogJSON is the normalized kingfisher rule catalog, generated by
// pkg/secretscan/secretgen (regenerate via `make update-secret-rules`).
//
//go:embed catalog.json
var catalogJSON []byte

// LoadCatalog parses the embedded rule catalog.
func LoadCatalog() (*catalog.Catalog, error) {
	var c catalog.Catalog
	if err := json.Unmarshal(catalogJSON, &c); err != nil {
		return nil, fmt.Errorf("secretscan: parse embedded catalog: %w", err)
	}
	return &c, nil
}

var (
	defaultOnce sync.Once
	defaultDet  *Detector
	defaultErr  error
)

// defaultBodyCacheSize bounds the process-wide Detector's per-body result cache.
// Every consumer (passive module, known-issue batch, discovery crawl) rescans
// bodies that recur constantly — the same SPA shell on every route, a page
// re-fetched across discovery/spider/assessment passes, near-duplicate historical
// records in the project DB — and detection runs at ~MB/s while a SHA-256 is
// ~GB/s, so memoizing by body hash is a large, safe win. Bounded so a long-lived
// server can't grow it without limit; ~1–2 MB of Match slices at this size.
const defaultBodyCacheSize = 8192

// Default returns a process-wide Detector built from the embedded catalog with
// default options (visible rules only). The catalog is parsed and all rule
// regexes compiled exactly once, then reused across scans. The per-body result
// cache is enabled (see defaultBodyCacheSize); the experimental Set prefilter is
// not (opt-in via New with Options.UseRegexSet).
func Default() (*Detector, error) {
	defaultOnce.Do(func() {
		cat, err := LoadCatalog()
		if err != nil {
			defaultErr = err
			return
		}
		defaultDet, defaultErr = New(cat, Options{BodyCacheSize: defaultBodyCacheSize})
	})
	return defaultDet, defaultErr
}
