var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/unauthorized/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0bnarw8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0ht-hir.js")
R.c("server/chunks/ssr/[root-of-the-server]__08un0-y._.js")
R.c("server/chunks/ssr/[root-of-the-server]__12pgiyg._.js")
R.c("server/chunks/ssr/src_app_layout_tsx_0e7l2q7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_unauthorized_page_actions_0onaczq.js")
R.m(2273)
module.exports=R.m(2273).exports
