var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/source-repos/[[...id]]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0-b_o6f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0~.p84k.js")
R.c("server/chunks/ssr/[root-of-the-server]__08un0-y._.js")
R.c("server/chunks/ssr/[root-of-the-server]__12pgiyg._.js")
R.c("server/chunks/ssr/src_app_layout_tsx_0e7l2q7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_source-repos_[[___id]]_page_actions_0h03v.v.js")
R.m(549)
module.exports=R.m(549).exports
