// Command secretgen normalizes the kingfisher secret-detection rule set into a
// single RE2-compatible catalog embedded by pkg/secretscan. It is run via
// `make update-secret-rules`, not at build time.
//
// The gitleaks/betterleaks rule family was removed: its keyword-proximity
// generic rules ("Generic API Key", "AWS secret access key") were the dominant
// false-positive source (matching reCAPTCHA site keys, hex digests, and
// minified-JS tokens as credentials), and every provider-specific rule it
// carried is covered by a better-anchored kingfisher pattern.
//
// Usage:
//
//	secretgen \
//	  -kingfisher <dir with kingfisher data/rules/*.yml> \
//	  -kingfisher-version v1.106.0 \
//	  -out pkg/secretscan/catalog.json \
//	  -examples-out pkg/secretscan/testdata/examples.json
package main

import (
	"encoding/base64"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/vigolium/vigolium/pkg/secretscan/catalog"
)

type droppedRule struct {
	ID      string
	Source  string
	Reason  string
	Pattern string
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "secretgen:", err)
		os.Exit(1)
	}
}

func run() error {
	var (
		kfDir       = flag.String("kingfisher", "", "path to kingfisher data/rules directory (*.yml)")
		kfVer       = flag.String("kingfisher-version", "", "kingfisher version pin, recorded in the catalog")
		out         = flag.String("out", "pkg/secretscan/catalog.json", "output catalog path")
		examplesOut = flag.String("examples-out", "pkg/secretscan/testdata/examples.json", "output example-corpus path")
	)
	flag.Parse()

	if *kfDir == "" {
		return fmt.Errorf("-kingfisher is required")
	}

	kfRules, examples, dropped, err := loadKingfisher(*kfDir)
	if err != nil {
		return err
	}
	rules := kfRules
	fmt.Fprintf(os.Stderr, "kingfisher: %d rules, %d dropped\n", len(kfRules), len(dropped))

	rules, dupes := dedupe(rules)
	sort.Slice(rules, func(i, j int) bool { return rules[i].ID < rules[j].ID })

	cat := catalog.Catalog{
		KingfisherVersion: *kfVer,
		Generated:         "generated by pkg/secretscan/secretgen — do not edit by hand",
		Rules:             rules,
	}

	if err := writeJSON(*out, cat); err != nil {
		return err
	}
	// Keep only examples for rules that survived compile+dedupe.
	kept := map[string]struct{}{}
	for _, r := range rules {
		kept[r.ID] = struct{}{}
	}
	prunedExamples := map[string][]string{}
	for id, ex := range examples {
		if _, ok := kept[id]; ok {
			prunedExamples[id] = ex
		}
	}
	// Store the example corpus XOR-obfuscated then base64-encoded so the on-disk
	// fixture isn't a live blob of provider-shaped secrets. Plain base64 is not
	// enough — secret scanners decode base64 and match the plaintext — so XOR
	// the bytes with a fixed key first. loadExamples in detector_test.go reverses it.
	for id, vals := range prunedExamples {
		for i, v := range vals {
			b := []byte(v)
			for j := range b {
				b[j] ^= 0x5A
			}
			prunedExamples[id][i] = base64.StdEncoding.EncodeToString(b)
		}
	}
	if err := writeJSON(*examplesOut, prunedExamples); err != nil {
		return err
	}

	report(rules, dropped, dupes)
	return nil
}

// compileCheck validates a normalized pattern against Go's RE2 engine. The
// runtime engine (go-re2) runs the same RE2 semantics, so a pattern that
// compiles here compiles at runtime. Returns a bucketed failure reason on error.
func compileCheck(pat string) (string, bool) {
	if _, err := regexp.Compile(pat); err != nil {
		msg := err.Error()
		if i := strings.LastIndex(msg, ": "); i >= 0 {
			msg = msg[i+2:]
		}
		return msg, false
	}
	return "", true
}

// dedupe drops rules whose normalized regex exactly matches an earlier rule
// (a few kingfisher rules share an identical normalized pattern). Returns the
// count removed.
func dedupe(in []catalog.Rule) ([]catalog.Rule, int) {
	seen := map[string]struct{}{}
	out := in[:0:0]
	dupes := 0
	for _, r := range in {
		if _, ok := seen[r.Re]; ok {
			dupes++
			continue
		}
		seen[r.Re] = struct{}{}
		out = append(out, r)
	}
	return out, dupes
}

func writeJSON(path string, v any) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	b, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		return err
	}
	b = append(b, '\n')
	return os.WriteFile(path, b, 0o644)
}

func report(rules []catalog.Rule, dropped []droppedRule, dupes int) {
	alwaysRun, invisible, withEntropy, withReqs := 0, 0, 0, 0
	for _, r := range rules {
		if len(r.Kw) == 0 {
			alwaysRun++
		}
		if !r.Visible {
			invisible++
		}
		if r.Entropy > 0 {
			withEntropy++
		}
		if r.MinDigits+r.MinLower+r.MinUpper+r.MinSpecial > 0 {
			withReqs++
		}
	}
	fmt.Fprintln(os.Stderr, "======== secretgen catalog report ========")
	fmt.Fprintf(os.Stderr, "total rules:        %d  (kingfisher)\n", len(rules))
	fmt.Fprintf(os.Stderr, "exact-dup dropped:  %d\n", dupes)
	fmt.Fprintf(os.Stderr, "compile-fail drop:  %d\n", len(dropped))
	fmt.Fprintf(os.Stderr, "always-run (no kw): %d  (%.1f%%)\n", alwaysRun, 100*float64(alwaysRun)/float64(max(len(rules), 1)))
	fmt.Fprintf(os.Stderr, "invisible (off):    %d\n", invisible)
	fmt.Fprintf(os.Stderr, "with entropy gate:  %d\n", withEntropy)
	fmt.Fprintf(os.Stderr, "with char reqs:     %d\n", withReqs)

	if len(dropped) > 0 {
		buckets := map[string]int{}
		for _, d := range dropped {
			buckets[d.Reason]++
		}
		type kv struct {
			k string
			v int
		}
		var bs []kv
		for k, v := range buckets {
			bs = append(bs, kv{k, v})
		}
		sort.Slice(bs, func(i, j int) bool { return bs[i].v > bs[j].v })
		fmt.Fprintln(os.Stderr, "---- dropped reasons ----")
		for _, b := range bs {
			fmt.Fprintf(os.Stderr, "  %3d  %s\n", b.v, b.k)
		}
		fmt.Fprintln(os.Stderr, "---- dropped rule ids ----")
		for _, d := range dropped {
			fmt.Fprintf(os.Stderr, "  [%s] %s: %s\n", d.Source, d.ID, d.Reason)
		}
	}
}
