var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/team/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0kk8bf0._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0f833pj.js")
R.c("server/chunks/ssr/[root-of-the-server]__08un0-y._.js")
R.c("server/chunks/ssr/[root-of-the-server]__12pgiyg._.js")
R.c("server/chunks/ssr/src_app_layout_tsx_0e7l2q7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_team_page_actions_0~v.fsg.js")
R.m(15681)
module.exports=R.m(15681).exports
