interface Props {
  vigoliumVersion?: string;
}

export default function Footer({ vigoliumVersion }: Props) {
  const date = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return (
    <footer className="px-4 pb-2 mt-2">
      <p className="text-center text-xs text-text-muted small-caps tracking-widest border-t border-warm-border pt-2">
        Generated by Vigolium{vigoliumVersion ? ` v${vigoliumVersion}` : ""} &middot; {date}
      </p>
      <p className="text-center text-[10px] text-text-muted mt-1">
        Crafted with &lt;3 by{" "}
        <a href="https://twitter.com/j3ssie" className="text-terracotta hover:text-charcoal transition-colors" target="_blank" rel="noopener noreferrer">@j3ssie</a>
      </p>
    </footer>
  );
}
