interface Props {
  vigoliumVersion?: string;
  generatedAt?: string;
}

export default function Footer({ vigoliumVersion, generatedAt }: Props) {
  const version = vigoliumVersion ?? "v0.1.0-alpha";
  const stamp = generatedAt ?? "2026-04-18T18:33:55.082Z";

  return (
    <footer
      className="footer no-print wrap"
      style={{
        paddingTop: 0,
        marginTop: 0,
        borderTop: "none",
        flexDirection: "column",
        alignItems: "stretch",
      }}
    >
      <span
        style={{
          textAlign: "center",
          fontStyle: "italic",
          marginBottom: 4,
        }}
      >
        All findings are preliminary and have not yet gone through the confirmation stage or human
        review. They may include intended functionality or false positives.
      </span>
      <div
        style={{
          borderTop: "1px solid var(--v-border)",
          paddingTop: 14,
          display: "flex",
          justifyContent: "space-between",
          flexWrap: "wrap",
          gap: 10,
        }}
      >
        <span>
          Generated by Vigolium {version}
          {" · "}
          <span style={{ color: "var(--v-error)" }}>{stamp}</span>
        </span>
        <span>
          Crafted with <span style={{ color: "var(--v-error)" }}>&lt;3</span> by{" "}
          <a href="https://twitter.com/j3ssie" target="_blank" rel="noopener noreferrer">
            @j3ssie
          </a>
        </span>
      </div>
    </footer>
  );
}
