interface Props {
  vigoliumVersion?: string;
  generatedAt?: string;
}

export default function Footer({ vigoliumVersion, generatedAt }: Props) {
  const date = generatedAt || new Date().toISOString();

  return (
    <footer className="px-4 pb-1 mt-1">
      <p className="text-center text-xs text-text-muted small-caps tracking-widest border-t border-warm-border pt-2">
        Generated by Vigolium{vigoliumVersion ? ` v${vigoliumVersion}` : ""} &middot; {date}
      </p>
      <p className="text-center text-[10px] text-text-muted mt-1">
        Crafted with <span className="text-rose">&lt;3</span> by{" "}
        <a href="https://twitter.com/j3ssie" className="text-terracotta hover:text-charcoal transition-colors" target="_blank" rel="noopener noreferrer">@j3ssie</a>
      </p>
    </footer>
  );
}
