var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/convex/credits/route.js")
R.c("server/chunks/[root-of-the-server]__0cbiqrd._.js")
R.c("server/chunks/node_modules_next_03e_drb._.js")
R.c("server/chunks/node_modules_next_124cnn1._.js")
R.c("server/chunks/[root-of-the-server]__0.6bt.6._.js")
R.c("server/chunks/src_lib_convex-billing_ts_0y0t7_s._.js")
R.c("server/chunks/[root-of-the-server]__0a7cvxw._.js")
R.c("server/chunks/_next-internal_server_app_api_convex_credits_route_actions_0j5xyx7.js")
R.m(88788)
module.exports=R.m(88788).exports
