var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/findings/[[...id]]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0-8-31s._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_10.4ris.js")
R.c("server/chunks/ssr/[root-of-the-server]__0-uz.o1._.js")
R.c("server/chunks/ssr/[root-of-the-server]__12pgiyg._.js")
R.c("server/chunks/ssr/src_app_layout_tsx_0e7l2q7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_findings_[[___id]]_page_actions_0v_3yh5.js")
R.m(6117)
module.exports=R.m(6117).exports
