var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/billing/portal/route.js")
R.c("server/chunks/[root-of-the-server]__06al-dp._.js")
R.c("server/chunks/[root-of-the-server]__0gbgxty._.js")
R.c("server/chunks/node_modules_next_124cnn1._.js")
R.c("server/chunks/[root-of-the-server]__0a7cvxw._.js")
R.c("server/chunks/[root-of-the-server]__0.6bt.6._.js")
R.c("server/chunks/node_modules_next_03e_drb._.js")
R.c("server/chunks/_next-internal_server_app_api_billing_portal_route_actions_063095p.js")
R.m(98946)
module.exports=R.m(98946).exports
