var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/proxy/[...path]/route.js")
R.c("server/chunks/[root-of-the-server]__0msnwq3._.js")
R.c("server/chunks/node_modules_jose_dist_webapi_jwt_sign_09zz_xa.js")
R.c("server/chunks/node_modules_next_124cnn1._.js")
R.c("server/chunks/node_modules_next_03e_drb._.js")
R.c("server/chunks/[root-of-the-server]__0a7cvxw._.js")
R.c("server/chunks/[root-of-the-server]__0.6bt.6._.js")
R.c("server/chunks/[root-of-the-server]__0gbgxty._.js")
R.c("server/chunks/src_lib_convex-billing_ts_0y0t7_s._.js")
R.c("server/chunks/_next-internal_server_app_api_proxy_[___path]_route_actions_0n.xh4s.js")
R.m(90519)
module.exports=R.m(90519).exports
