package agent

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"github.com/vigolium/vigolium/pkg/modules"
	"go.uber.org/zap"
)

// PipelinePhase identifies a phase in the multi-phase scanning pipeline.
type PipelinePhase string

const (
	PhaseSourceAnalysis PipelinePhase = "source-analysis"
	PhaseDiscover       PipelinePhase = "discover"
	PhasePlan           PipelinePhase = "plan"
	PhaseScan           PipelinePhase = "scan"
	PhaseTriage         PipelinePhase = "triage"
	PhaseRescan         PipelinePhase = "rescan"
	PhaseReport         PipelinePhase = "report"
)

// AllPipelinePhases returns the ordered list of pipeline phases.
func AllPipelinePhases() []PipelinePhase {
	return []PipelinePhase{
		PhaseSourceAnalysis, PhaseDiscover, PhasePlan, PhaseScan,
		PhaseTriage, PhaseRescan, PhaseReport,
	}
}

// AttackPlan is the structured output from the plan agent checkpoint (phase 2).
// The agent analyzes discovery results and produces a scanning strategy.
type AttackPlan struct {
	ModuleTags []string          `json:"module_tags,omitempty"`
	ModuleIDs  []string          `json:"module_ids,omitempty"`
	FocusAreas []string          `json:"focus_areas,omitempty"`
	SkipPaths  []string          `json:"skip_paths,omitempty"`
	Endpoints  []PlannedEndpoint `json:"endpoints,omitempty"`
	Notes      string            `json:"notes,omitempty"`
}

// attackPlanHasContent returns true if the plan has at least one meaningful field.
func attackPlanHasContent(plan *AttackPlan) bool {
	if plan == nil {
		return false
	}
	return len(plan.ModuleTags) > 0 ||
		len(plan.ModuleIDs) > 0 ||
		len(plan.FocusAreas) > 0 ||
		len(plan.SkipPaths) > 0 ||
		len(plan.Endpoints) > 0 ||
		plan.Notes != ""
}

// PlannedEndpoint represents a prioritized endpoint in the attack plan.
type PlannedEndpoint struct {
	URL       string   `json:"url"`
	Method    string   `json:"method,omitempty"`
	Priority  string   `json:"priority"` // high, medium, low
	Rationale string   `json:"rationale,omitempty"`
	Tags      []string `json:"tags,omitempty"`
}

// TriageResult is the structured output from the triage agent checkpoint (phase 4).
// The agent reviews findings and decides whether additional scanning is needed.
type TriageResult struct {
	Confirmed      []TriagedFinding `json:"confirmed"`
	FalsePositives []TriagedFinding `json:"false_positives"`
	FollowUps      []FollowUpScan   `json:"follow_up_scans,omitempty"`
	Verdict        string           `json:"verdict"` // "done" or "rescan"
	Notes          string           `json:"notes,omitempty"`
}

// TriagedFinding is a finding that has been reviewed by the triage agent.
type TriagedFinding struct {
	Title    string `json:"title"`
	ModuleID string `json:"module_id,omitempty"`
	URL      string `json:"url,omitempty"`
	Reason   string `json:"reason,omitempty"`
}

// FollowUpScan describes a targeted rescan recommended by the triage agent.
type FollowUpScan struct {
	URL        string   `json:"url"`
	Method     string   `json:"method,omitempty"`
	ModuleTags []string `json:"module_tags,omitempty"`
	ModuleIDs  []string `json:"module_ids,omitempty"`
	Rationale  string   `json:"rationale,omitempty"`
}

// SourceAnalysisResult is the structured output from the source analysis phase (phase 0).
// The agent explores source code and extracts routes, session config, and custom extensions.
type SourceAnalysisResult struct {
	HTTPRecords   []AgentHTTPRecord    `json:"http_records"`
	SessionConfig *AgentSessionConfig  `json:"session_config,omitempty"`
	Extensions    []GeneratedExtension `json:"extensions,omitempty"`
}

// AgentSessionConfig holds session definitions generated by the source analysis agent.
type AgentSessionConfig struct {
	Sessions []AgentSessionEntry `json:"sessions"`
}

// AgentSessionEntry represents a single session identity for authenticated scanning.
type AgentSessionEntry struct {
	Name    string            `json:"name"`
	Role    string            `json:"role"`              // "primary" or "compare"
	Headers map[string]string `json:"headers,omitempty"` // static auth headers
	Login   *AgentLoginFlow   `json:"login,omitempty"`   // login-based auth
}

// AgentLoginFlow defines a login flow discovered from source code analysis.
type AgentLoginFlow struct {
	URL         string             `json:"url"`
	Method      string             `json:"method"`
	ContentType string             `json:"content_type,omitempty"`
	Body        string             `json:"body,omitempty"`
	Extract     []AgentExtractRule `json:"extract"`
}

// AgentExtractRule defines how to extract an auth token from a login response.
type AgentExtractRule struct {
	Source  string `json:"source"`             // "cookie", "json", "header"
	Name    string `json:"name,omitempty"`     // cookie name or header name
	Path    string `json:"path,omitempty"`     // JSONPath for json source
	ApplyAs string `json:"apply_as,omitempty"` // e.g. "Authorization: Bearer {value}"
}

// GeneratedExtension represents a JavaScript extension generated by the agent.
type GeneratedExtension struct {
	Filename string `json:"filename"`
	Code     string `json:"code"`
	Reason   string `json:"reason"`
}

// sanitizeExtensionFilename ensures a filename is safe for writing to disk.
// It strips path components to prevent traversal and falls back to a
// numbered default for empty or dot-only names.
func sanitizeExtensionFilename(name string, index int) string {
	name = filepath.Base(name)
	if name == "" || name == "." || name == ".." {
		return fmt.Sprintf("extension-%d.js", index)
	}
	return name
}

// QuickCheck is a declarative shorthand for simple payload-and-match scan checks.
// The swarm runner auto-generates a full JS extension from each QuickCheck.
type QuickCheck struct {
	ID       string              `json:"id"`
	Severity string              `json:"severity,omitempty"` // default: "medium"
	Scan     string              `json:"scan"`               // "per_insertion_point", "per_request", "per_host"
	Payloads []string            `json:"payloads,omitempty"` // for per_insertion_point: payloads to inject
	Requests []QuickCheckRequest `json:"requests,omitempty"` // for per_request/per_host: requests to send
	Match    QuickCheckMatch     `json:"match"`
}

// QuickCheckRequest defines a request to send in per_request/per_host quick checks.
type QuickCheckRequest struct {
	Method  string            `json:"method"`
	Path    string            `json:"path"`
	Headers map[string]string `json:"headers,omitempty"`
	Body    string            `json:"body,omitempty"`
}

// QuickCheckMatch defines match conditions for a quick check (OR logic).
type QuickCheckMatch struct {
	BodyContains   string `json:"body_contains,omitempty"`
	BodyRegex      string `json:"body_regex,omitempty"`
	Status         int    `json:"status,omitempty"`
	HeaderContains string `json:"header_contains,omitempty"`
}

// Snippet is a shorthand extension where only the scan function body is provided.
// The swarm runner wraps it in a full module scaffold with access to ctx, insertion, and vigolium.* APIs.
type Snippet struct {
	ID       string `json:"id"`
	Severity string `json:"severity,omitempty"` // default: "medium"
	Scan     string `json:"scan"`               // "per_insertion_point", "per_request", "per_host"
	Body     string `json:"body"`               // JS function body
}

// SwarmPlan is the structured output from the master agent in agent swarm mode.
// The agent analyzes the target request, selects modules, and generates custom extensions.
type SwarmPlan struct {
	ModuleTags  []string             `json:"module_tags,omitempty"`
	ModuleIDs   []string             `json:"module_ids,omitempty"`
	Extensions  []GeneratedExtension `json:"extensions,omitempty"`
	QuickChecks []QuickCheck         `json:"quick_checks,omitempty"`
	Snippets    []Snippet            `json:"snippets,omitempty"`
	FocusAreas  []string             `json:"focus_areas,omitempty"`
	Notes       string               `json:"notes,omitempty"`
}

// BatchProvenance tracks which batch contributed each item to a merged plan.
type BatchProvenance struct {
	ModuleTags map[string]int `json:"module_tags,omitempty"` // tag -> batch number
	ModuleIDs  map[string]int `json:"module_ids,omitempty"`  // id -> batch number
	Extensions map[string]int `json:"extensions,omitempty"`  // filename -> batch number
	FocusAreas map[string]int `json:"focus_areas,omitempty"` // focus area -> batch number
}

// TokenUsage tracks cumulative token consumption across agent calls in a run.
type TokenUsage struct {
	InputTokens  int `json:"input_tokens"`
	OutputTokens int `json:"output_tokens"`
}

// ProgressEvent reports granular progress during agent scans.
type ProgressEvent struct {
	Phase        string `json:"phase"`
	SubPhase     string `json:"sub_phase,omitempty"`
	Current      int    `json:"current,omitempty"`
	Total        int    `json:"total,omitempty"`
	FindingCount int    `json:"finding_count,omitempty"`
	Message      string `json:"message,omitempty"`
}

// SwarmResult holds the outcome of an agent swarm run.
type SwarmResult struct {
	SwarmPlan      *SwarmPlan      `json:"swarm_plan,omitempty"`
	TriageResults  []*TriageResult `json:"triage_results,omitempty"`
	TotalFindings  int             `json:"total_findings"`
	TotalRecords   int             `json:"total_records"`
	SeverityCounts map[string]int  `json:"severity_counts,omitempty"` // critical, high, medium, low, info
	Confirmed      int             `json:"confirmed"`
	FalsePositives int             `json:"false_positives"`
	Iterations     int             `json:"iterations"`
	Duration       time.Duration   `json:"duration"`
	AgentRunUUID   string          `json:"agent_run_uuid"`
	SessionID      string          `json:"session_id,omitempty"`  // last ACP session ID (for single or last batch)
	SessionIDs     []string        `json:"session_ids,omitempty"` // all ACP session IDs when batched (>5 records); nil for single-batch runs
	SessionDir      string                         `json:"session_dir,omitempty"`
	PhaseTimings    map[string]time.Duration       `json:"phase_timings,omitempty"`
	TokenUsage      TokenUsage                     `json:"token_usage,omitempty"`
	BatchProvenance *BatchProvenance               `json:"batch_provenance,omitempty"` // only set when plan was merged from multiple batches
}

// SwarmCheckpoint captures swarm pipeline state for checkpoint/resume.
type SwarmCheckpoint struct {
	CompletedPhases  []string            `json:"completed_phases"`
	TargetURL        string              `json:"target_url"`
	RecordCount      int                 `json:"record_count"`
	Plan             *SwarmPlan          `json:"plan,omitempty"`
	ExtensionDir     string              `json:"extension_dir,omitempty"`
	Timestamp        time.Time           `json:"timestamp"`
	TriageRound      int                 `json:"triage_round,omitempty"`       // last completed triage round (0-indexed)
	ExtensionRenames map[string]string   `json:"extension_renames,omitempty"`  // original filename -> renamed filename
}

// LastPhase returns the last completed phase, or "" if none.
func (cp *SwarmCheckpoint) LastPhase() string {
	if cp == nil || len(cp.CompletedPhases) == 0 {
		return ""
	}
	return cp.CompletedPhases[len(cp.CompletedPhases)-1]
}

// writeCheckpoint persists a SwarmCheckpoint to the session directory.
func writeCheckpoint(sessionDir string, cp *SwarmCheckpoint) error {
	if sessionDir == "" {
		return nil
	}
	data, err := json.MarshalIndent(cp, "", "  ")
	if err != nil {
		return fmt.Errorf("failed to marshal checkpoint: %w", err)
	}
	return os.WriteFile(filepath.Join(sessionDir, "checkpoint.json"), data, 0644)
}

// loadCheckpoint reads a SwarmCheckpoint from the session directory.
func loadCheckpoint(sessionDir string) (*SwarmCheckpoint, error) {
	data, err := os.ReadFile(filepath.Join(sessionDir, "checkpoint.json"))
	if err != nil {
		return nil, err
	}
	var cp SwarmCheckpoint
	if err := json.Unmarshal(data, &cp); err != nil {
		return nil, fmt.Errorf("failed to parse checkpoint: %w", err)
	}
	return &cp, nil
}

// swarmPlanWrapper wraps SwarmPlan for JSON parsing flexibility.
type swarmPlanWrapper struct {
	Plan SwarmPlan `json:"swarm_plan"`
}

// ParseSwarmPlan extracts a SwarmPlan from raw agent output.
// It supports two formats:
//  1. Legacy: a single JSON object containing all fields including extensions[].code
//  2. Hybrid: a single-line JSON plan (module_tags, module_ids, focus_areas, notes)
//     followed by fenced ```javascript code blocks for extensions. Each extension
//     is preceded by a heading like "#### filename.js" and optionally "Reason: ...".
//
// module_tags is optional — when absent the downstream scan runs all modules.
func ParseSwarmPlan(raw string) (*SwarmPlan, error) {
	// Try markdown section format first (most robust for LLM output)
	if plan, err := parseSwarmPlanMarkdown(raw); err == nil && swarmPlanHasContent(plan) {
		return plan, nil
	}

	// Try hybrid format: JSONL plan line + fenced code blocks for extensions
	if plan, err := parseSwarmPlanHybrid(raw); err == nil && swarmPlanHasContent(plan) {
		return plan, nil
	}

	// Try all valid JSON blocks looking for one with recognizable plan fields
	for _, block := range findAllJSONBlocks(raw) {
		if !isJSON(block) {
			continue
		}
		var wrapper swarmPlanWrapper
		if json.Unmarshal([]byte(block), &wrapper) == nil && swarmPlanHasContent(&wrapper.Plan) {
			return &wrapper.Plan, nil
		}
		var plan SwarmPlan
		if json.Unmarshal([]byte(block), &plan) == nil && swarmPlanHasContent(&plan) {
			return &plan, nil
		}
	}

	// Last resort: regex-extract fields from garbled JSON.
	if plan := extractSwarmPlanRegex(raw); plan != nil {
		zap.L().Info("Recovered swarm plan via regex fallback",
			zap.Int("module_tags", len(plan.ModuleTags)))
		return plan, nil
	}

	return nil, fmt.Errorf("failed to parse swarm plan: no recognizable plan structure found")
}

// swarmPlanHasContent returns true if the plan contains at least one meaningful field.
// module_tags is no longer required — a plan with only focus_areas, extensions, etc. is valid.
func swarmPlanHasContent(plan *SwarmPlan) bool {
	if plan == nil {
		return false
	}
	return len(plan.ModuleTags) > 0 ||
		len(plan.ModuleIDs) > 0 ||
		len(plan.Extensions) > 0 ||
		len(plan.QuickChecks) > 0 ||
		len(plan.Snippets) > 0 ||
		len(plan.FocusAreas) > 0 ||
		plan.Notes != ""
}

// moduleTagsRegex matches a "module_tags" JSON array in possibly garbled text.
var moduleTagsRegex = regexp.MustCompile(`"module_tags"\s*:\s*\[((?:"[^"]*"(?:\s*,\s*)?)*)\]`)

// moduleIDsRegex matches a "module_ids" JSON array in possibly garbled text.
var moduleIDsRegex = regexp.MustCompile(`"module_ids"\s*:\s*\[((?:"[^"]*"(?:\s*,\s*)?)*)\]`)

// focusAreasRegex matches a "focus_areas" JSON array.
var focusAreasRegex = regexp.MustCompile(`"focus_areas"\s*:\s*\[((?:"[^"]*"(?:\s*,\s*)?)*)\]`)

// notesRegex matches a "notes" JSON string.
var notesRegex = regexp.MustCompile(`"notes"\s*:\s*"((?:[^"\\]|\\.)*)"`)

// extractSwarmPlanRegex attempts to recover a minimal SwarmPlan from garbled JSON
// by regex-extracting individual fields. Returns nil if no recognizable fields are found.
func extractSwarmPlanRegex(raw string) *SwarmPlan {
	plan := &SwarmPlan{}

	// Try extracting module_tags (optional)
	if m := moduleTagsRegex.FindStringSubmatch(raw); len(m) >= 2 {
		var tags []string
		if json.Unmarshal([]byte("["+m[1]+"]"), &tags) == nil {
			plan.ModuleTags = tags
		}
	}

	// Try extracting module_ids (optional)
	if m := moduleIDsRegex.FindStringSubmatch(raw); len(m) >= 2 {
		var ids []string
		if json.Unmarshal([]byte("["+m[1]+"]"), &ids) == nil {
			plan.ModuleIDs = ids
		}
	}

	// Best-effort extraction of other fields
	if fm := focusAreasRegex.FindStringSubmatch(raw); len(fm) >= 2 {
		var fa []string
		if json.Unmarshal([]byte("["+fm[1]+"]"), &fa) == nil {
			plan.FocusAreas = fa
		}
	}
	if nm := notesRegex.FindStringSubmatch(raw); len(nm) >= 2 {
		plan.Notes = nm[1]
	}

	// Extract code block extensions (hybrid format)
	if codeExts := extractCodeBlockExtensions(raw); len(codeExts) > 0 {
		plan.Extensions = codeExts
	}

	if !swarmPlanHasContent(plan) {
		return nil
	}
	return plan
}

// parseSwarmPlanHybrid parses the hybrid output format where the plan JSON is a
// single line and extensions are in fenced ```javascript code blocks.
func parseSwarmPlanHybrid(raw string) (*SwarmPlan, error) {
	lines := strings.Split(raw, "\n")

	// Step 1: Find and parse the plan JSON line — look for lines containing known plan fields.
	planKeys := []string{"\"module_tags\"", "\"module_ids\"", "\"focus_areas\"", "\"extensions\"", "\"quick_checks\"", "\"snippets\""}
	var plan SwarmPlan
	planFound := false
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		hasPlanKey := false
		for _, key := range planKeys {
			if strings.Contains(line, key) {
				hasPlanKey = true
				break
			}
		}
		if !hasPlanKey {
			continue
		}
		if json.Unmarshal([]byte(line), &plan) == nil && swarmPlanHasContent(&plan) {
			planFound = true
			break
		}
		// Also try extracting JSON from this line (in case of surrounding text)
		if extracted := findJSONBlock(line); extracted != "" {
			if json.Unmarshal([]byte(extracted), &plan) == nil && swarmPlanHasContent(&plan) {
				planFound = true
				break
			}
		}
	}

	// Fallback: try all JSON blocks in the full text (handles corrupted first block + valid later block)
	if !planFound {
		for _, block := range findAllJSONBlocks(raw) {
			if json.Unmarshal([]byte(block), &plan) == nil && swarmPlanHasContent(&plan) {
				planFound = true
				break
			}
		}
	}

	if !planFound {
		return nil, fmt.Errorf("no plan JSON line found")
	}

	// Step 2: Extract fenced JavaScript code blocks as extensions (supplement, don't overwrite)
	if codeExts := extractCodeBlockExtensions(raw); len(codeExts) > 0 {
		plan.Extensions = append(plan.Extensions, codeExts...)
	}

	return &plan, nil
}

// parseSwarmPlanMarkdown parses the markdown section format where the LLM outputs
// structured sections with ## headings instead of a single JSON blob.
// This format is inherently more robust against LLM token-level corruption.
func parseSwarmPlanMarkdown(raw string) (*SwarmPlan, error) {
	sections := splitMarkdownSections(raw)

	// At least one recognized section must be present for this to be a markdown-format plan.
	recognizedSections := []string{"MODULE_TAGS", "MODULE_IDS", "FOCUS_AREAS", "NOTES"}
	hasSection := false
	for _, name := range recognizedSections {
		if _, ok := sections[name]; ok {
			hasSection = true
			break
		}
	}
	if !hasSection {
		return nil, fmt.Errorf("no recognized markdown sections found")
	}

	plan := &SwarmPlan{}

	if tagsRaw, ok := sections["MODULE_TAGS"]; ok {
		plan.ModuleTags = parseCommaSeparated(tagsRaw)
	}

	if idsRaw, ok := sections["MODULE_IDS"]; ok {
		plan.ModuleIDs = parseCommaSeparated(idsRaw)
	}

	if faRaw, ok := sections["FOCUS_AREAS"]; ok {
		plan.FocusAreas = parseBulletList(faRaw)
	}

	if notes, ok := sections["NOTES"]; ok {
		plan.Notes = strings.TrimSpace(notes)
	}

	// Extract extensions from fenced code blocks (existing logic handles #### headings)
	if codeExts := extractCodeBlockExtensions(raw); len(codeExts) > 0 {
		plan.Extensions = codeExts
	}

	// Extract quick_checks from JSON — try keyed field first, then standalone arrays in fences
	if qcBlock := findJSONArrayInSection(raw, "quick_checks"); qcBlock != "" {
		var qcs []QuickCheck
		if json.Unmarshal([]byte(qcBlock), &qcs) == nil {
			plan.QuickChecks = qcs
		}
	}
	if len(plan.QuickChecks) == 0 {
		// Try fenced JSON blocks as standalone quick check arrays
		for _, fenced := range extractFencedBlocks(raw) {
			fenced = strings.TrimSpace(fenced)
			if fenced == "" || fenced[0] != '[' {
				continue
			}
			var qcs []QuickCheck
			if json.Unmarshal([]byte(fenced), &qcs) == nil && len(qcs) > 0 && qcs[0].ID != "" {
				plan.QuickChecks = qcs
				break
			}
		}
	}

	return plan, nil
}

// splitMarkdownSections splits text by ## headings and returns a map of section name to content.
func splitMarkdownSections(raw string) map[string]string {
	sections := make(map[string]string)
	lines := strings.Split(raw, "\n")

	var currentSection string
	var content strings.Builder

	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "## ") && !strings.HasPrefix(trimmed, "### ") {
			// Save previous section
			if currentSection != "" {
				sections[currentSection] = content.String()
			}
			currentSection = strings.TrimSpace(trimmed[3:])
			content.Reset()
			continue
		}
		if currentSection != "" {
			if content.Len() > 0 {
				content.WriteByte('\n')
			}
			content.WriteString(line)
		}
	}
	// Save last section
	if currentSection != "" {
		sections[currentSection] = content.String()
	}
	return sections
}

// parseCommaSeparated splits a string by commas and returns trimmed, non-empty tokens.
func parseCommaSeparated(s string) []string {
	var result []string
	for _, token := range strings.Split(s, ",") {
		token = strings.TrimSpace(token)
		if token != "" {
			result = append(result, token)
		}
	}
	return result
}

// parseBulletList extracts items from a bulleted markdown list.
func parseBulletList(s string) []string {
	var result []string
	for _, line := range strings.Split(s, "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "- ") {
			item := strings.TrimSpace(line[2:])
			if item != "" {
				result = append(result, item)
			}
		} else if strings.HasPrefix(line, "* ") {
			item := strings.TrimSpace(line[2:])
			if item != "" {
				result = append(result, item)
			}
		} else if line != "" {
			// Plain text line (not bulleted)
			result = append(result, line)
		}
	}
	return result
}

// findJSONArrayInSection searches for a JSON array associated with a key name in the raw text.
func findJSONArrayInSection(raw, key string) string {
	pattern := `"` + key + `"`
	idx := strings.Index(raw, pattern)
	if idx < 0 {
		return ""
	}
	// Find the '[' after the key
	rest := raw[idx+len(pattern):]
	for i, ch := range rest {
		if ch == '[' {
			block := findJSONBlockFrom(rest, i)
			if block != "" {
				return block
			}
		}
		if ch != ':' && ch != ' ' && ch != '\t' {
			break
		}
	}
	return ""
}

// extractCodeBlockExtensions extracts GeneratedExtension entries from fenced
// ```javascript code blocks in the raw output. It looks for heading patterns
// like "#### filename.js" or "### filename.js" before each block, and
// "Reason: ..." lines for the reason field.
func extractCodeBlockExtensions(raw string) []GeneratedExtension {
	var extensions []GeneratedExtension
	unnamedCounter := 0
	lines := strings.Split(raw, "\n")

	for i := 0; i < len(lines); i++ {
		trimmed := strings.TrimSpace(lines[i])

		// Look for opening fence: ```javascript or ```js
		if !isJSFenceOpen(trimmed) {
			continue
		}

		fenceLineIdx := i

		// Collect code until closing ```
		var code strings.Builder
		i++
		for i < len(lines) {
			if strings.TrimSpace(lines[i]) == "```" {
				break
			}
			if code.Len() > 0 {
				code.WriteByte('\n')
			}
			code.WriteString(lines[i])
			i++
		}

		codeStr := code.String()
		if codeStr == "" {
			continue
		}

		// Extract filename from a preceding heading (#### filename.js / ### filename.js)
		// and reason from a "Reason: ..." line. Scan backwards from the fence line.
		filename, reason := extractExtensionMeta(lines, fenceLineIdx)

		// If no heading filename, try to extract from module id in the code
		if filename == "" {
			filename = extractFilenameFromCode(codeStr)
		}
		if filename == "extension.js" {
			filename = fmt.Sprintf("extension-%d.js", unnamedCounter)
			unnamedCounter++
		}

		extensions = append(extensions, GeneratedExtension{
			Filename: filename,
			Code:     codeStr,
			Reason:   reason,
		})
	}

	return extensions
}

// isJSFenceOpen returns true if the line opens a JavaScript code fence.
func isJSFenceOpen(line string) bool {
	if strings.HasPrefix(line, "```javascript") {
		return true
	}
	// Match ```js but not ```json
	if strings.HasPrefix(line, "```js") && !strings.HasPrefix(line, "```json") {
		return true
	}
	return false
}

// extractExtensionMeta scans lines backwards from fenceIdx to find a heading
// containing a .js filename and an optional "Reason:" line.
func extractExtensionMeta(lines []string, fenceIdx int) (filename, reason string) {
	// Scan up to 5 lines backwards looking for metadata
	start := fenceIdx - 5
	if start < 0 {
		start = 0
	}
	for j := fenceIdx; j >= start; j-- {
		line := strings.TrimSpace(lines[j])

		// Heading with filename: "#### custom-check.js" or "### custom-check.js"
		if filename == "" && strings.HasPrefix(line, "#") {
			// Strip leading # characters and whitespace
			name := strings.TrimLeft(line, "# ")
			if strings.HasSuffix(name, ".js") {
				filename = name
			}
		}

		// Reason line
		if reason == "" && strings.HasPrefix(line, "Reason:") {
			reason = strings.TrimSpace(strings.TrimPrefix(line, "Reason:"))
		}
	}
	return filename, reason
}

// extractFilenameFromCode tries to extract a filename from the module id in JS code.
// It looks for patterns like id: "custom-something" and converts to custom-something.js.
func extractFilenameFromCode(code string) string {
	// Look for id: "..." or id: '...'
	for _, pattern := range []string{`id: "`, `id: '`, `id:"`, `id:'`} {
		idx := strings.Index(code, pattern)
		if idx < 0 {
			continue
		}
		start := idx + len(pattern)
		quote := code[start-1] // matching quote character
		end := strings.IndexByte(code[start:], quote)
		if end > 0 {
			return code[start:start+end] + ".js"
		}
	}
	return "extension.js"
}

// SourceAnalysisConfig configures a source analysis run. Used by both pipeline and swarm.
type SourceAnalysisConfig struct {
	AgentName      string
	AgentACPCmd    string // ad-hoc ACP command override (e.g. "traecli acp")
	TargetURL      string
	SourcePath     string
	Files          []string
	Instruction    string // user-provided custom instruction appended to the prompt
	PromptTemplate string // override template ID (default: "pipeline-source-analysis")
	DryRun         bool
	ShowPrompt     bool // print rendered prompt to stderr before executing
	ScanUUID       string
	ProjectUUID    string
	StreamWriter   io.Writer
}

// EnsureSessionDir creates the session directory for a given run ID under the specified base directory.
// If baseDir is empty, defaults to ~/.vigolium/agent-sessions/.
// Returns the absolute path to the created directory.
func EnsureSessionDir(baseDir, runID string) (string, error) {
	if baseDir == "" {
		home, err := os.UserHomeDir()
		if err != nil {
			return "", fmt.Errorf("failed to get home dir: %w", err)
		}
		baseDir = filepath.Join(home, ".vigolium", "agent-sessions")
	}
	dir := filepath.Join(baseDir, runID)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return "", fmt.Errorf("failed to create session dir: %w", err)
	}
	return dir, nil
}

// WriteExtensionsToSessionDir writes generated JavaScript extensions to <sessionDir>/extensions/
// and returns the extensions subdirectory path.
func WriteExtensionsToSessionDir(extensions []GeneratedExtension, sessionDir string) (string, error) {
	extDir := filepath.Join(sessionDir, "extensions")
	if err := os.MkdirAll(extDir, 0755); err != nil {
		return "", fmt.Errorf("failed to create extensions dir: %w", err)
	}
	for i, ext := range extensions {
		filename := sanitizeExtensionFilename(ext.Filename, i)
		path := filepath.Join(extDir, filename)
		if writeErr := os.WriteFile(path, []byte(ext.Code), 0644); writeErr != nil {
			zap.L().Warn("Failed to write extension",
				zap.String("filename", ext.Filename), zap.Error(writeErr))
			continue
		}
		zap.L().Info("Generated extension",
			zap.String("filename", ext.Filename),
			zap.String("reason", ext.Reason),
			zap.String("path", path))
	}
	return extDir, nil
}

// ScanRequest encapsulates parameters for a scan callback invocation.
// This unified type is shared by both Pipeline and Swarm modes.
type ScanRequest struct {
	ModuleTags   []string // module tags from the agent's plan
	ModuleIDs    []string // explicit module IDs from the agent's plan
	ExtensionDir string   // path to generated JS extensions (empty if none)
	IsRescan     bool     // true for triage-driven targeted rescans
}

// ScanFunc is the unified callback signature for running scans.
// Both Pipeline and Swarm modes use this type for their scan callbacks.
type ScanFunc func(ctx context.Context, req ScanRequest) error

// PipelineConfig configures a pipeline run.
type PipelineConfig struct {
	TargetURL       string
	AgentName       string
	AgentACPCmd     string // ad-hoc ACP command override (e.g. "traecli acp")
	Focus           string
	Instruction     string // user-provided custom instruction appended to agent prompts
	SourcePath      string
	Files           []string
	MaxRescanRounds int
	SkipPhases      map[PipelinePhase]bool
	StartFrom       PipelinePhase
	DryRun          bool
	ShowPrompt      bool // print rendered prompts to stderr before executing
	StreamWriter    io.Writer
	ProjectUUID     string
	ScanUUID        string

	// DiscoverFunc runs the discovery phase (deparos + spidering).
	// It should populate the database with HTTP records.
	DiscoverFunc func(ctx context.Context) error

	// ScanFunc runs the audit phase with the given module filters.
	ScanFunc ScanFunc

	// PhaseCallback is called when a pipeline phase starts.
	// Used by the API server to emit SSE phase events and update status.
	PhaseCallback func(phase PipelinePhase)

	// SourceAnalysisCallback is called after Phase 0 completes to allow the caller
	// to process generated extensions and session config (e.g. write to disk).
	SourceAnalysisCallback func(result *SourceAnalysisResult) error
}

// PipelineResult holds the outcome of a full pipeline run.
type PipelineResult struct {
	SourceAnalysis *SourceAnalysisResult `json:"source_analysis,omitempty"`
	Plan           *AttackPlan           `json:"plan,omitempty"`
	TriageResults  []*TriageResult       `json:"triage_results,omitempty"`
	TotalFindings  int                   `json:"total_findings"`
	Confirmed      int                   `json:"confirmed"`
	FalsePositives int                   `json:"false_positives"`
	RescanRounds   int                   `json:"rescan_rounds"`
	PhasesRun      []PipelinePhase                `json:"phases_run"`
	PhaseTimings   map[PipelinePhase]time.Duration `json:"phase_timings,omitempty"`
	Duration       time.Duration                  `json:"duration"`
	SessionID      string                         `json:"session_id,omitempty"` // ACP session ID for resume
	TokenUsage     TokenUsage                     `json:"token_usage,omitempty"`
}

// attackPlanWrapper wraps AttackPlan for JSON parsing flexibility.
type attackPlanWrapper struct {
	Plan AttackPlan `json:"plan"`
}

// triageResultWrapper wraps TriageResult for JSON parsing flexibility.
type triageResultWrapper struct {
	Triage TriageResult `json:"triage"`
}

// sourceAnalysisWrapper wraps SourceAnalysisResult for JSON parsing flexibility.
type sourceAnalysisWrapper struct {
	SourceAnalysis SourceAnalysisResult `json:"source_analysis"`
}

// ParseAttackPlan extracts an AttackPlan from raw agent output.
func ParseAttackPlan(raw string) (*AttackPlan, error) {
	jsonStr, err := extractJSON(raw)
	if err != nil {
		return nil, fmt.Errorf("failed to extract JSON from agent output: %w", err)
	}

	// Try wrapped format: {"plan": {...}}
	var wrapper attackPlanWrapper
	if err := json.Unmarshal([]byte(jsonStr), &wrapper); err == nil && attackPlanHasContent(&wrapper.Plan) {
		return &wrapper.Plan, nil
	}

	// Try direct format: {...}
	var plan AttackPlan
	if err := json.Unmarshal([]byte(jsonStr), &plan); err == nil && attackPlanHasContent(&plan) {
		return &plan, nil
	}

	return nil, fmt.Errorf("failed to parse attack plan from JSON: no recognizable plan structure found")
}

// ParseTriageResult extracts a TriageResult from raw agent output.
func ParseTriageResult(raw string) (*TriageResult, error) {
	jsonStr, err := extractJSON(raw)
	if err != nil {
		return nil, fmt.Errorf("failed to extract JSON from agent output: %w", err)
	}

	// Try wrapped format: {"triage": {...}}
	var wrapper triageResultWrapper
	if err := json.Unmarshal([]byte(jsonStr), &wrapper); err == nil && wrapper.Triage.Verdict != "" {
		return &wrapper.Triage, nil
	}

	// Try direct format: {...}
	var result TriageResult
	if err := json.Unmarshal([]byte(jsonStr), &result); err == nil && result.Verdict != "" {
		return &result, nil
	}

	return nil, fmt.Errorf("failed to parse triage result from JSON: invalid structure (expected verdict)")
}

// ParseSourceAnalysisResult extracts a SourceAnalysisResult from raw agent output.
// It supports two formats:
//  1. Hybrid: JSON object containing http_records and session_config, followed by
//     fenced ```javascript code blocks for extensions (preferred — avoids escaping issues).
//  2. Legacy: a single JSON object containing all fields including extensions[].code.
func ParseSourceAnalysisResult(raw string) (*SourceAnalysisResult, error) {
	// Try hybrid format first: JSON with records/session_config + fenced code blocks for extensions
	if result, err := parseSourceAnalysisHybrid(raw); err == nil && len(result.HTTPRecords) > 0 {
		return result, nil
	}

	// Fall back to legacy all-in-one JSON format
	jsonStr, err := extractJSON(raw)
	if err != nil {
		return nil, fmt.Errorf("failed to extract JSON from agent output: %w", err)
	}

	// Try wrapped format: {"source_analysis": {...}}
	var wrapper sourceAnalysisWrapper
	if err := json.Unmarshal([]byte(jsonStr), &wrapper); err == nil && len(wrapper.SourceAnalysis.HTTPRecords) > 0 {
		return &wrapper.SourceAnalysis, nil
	}

	// Try direct format: {...}
	var result SourceAnalysisResult
	if err := json.Unmarshal([]byte(jsonStr), &result); err != nil {
		return nil, fmt.Errorf("failed to parse source analysis result from JSON: %w", err)
	}

	return &result, nil
}

// parseSourceAnalysisHybrid parses the hybrid output format where the JSON contains
// http_records and session_config, and extensions are in fenced ```javascript code blocks.
func parseSourceAnalysisHybrid(raw string) (*SourceAnalysisResult, error) {
	// Try extracting JSON from a ```json fenced block first (preferred — unambiguous anchor).
	// Fall back to generic extractJSON() for backward compatibility with raw-JSON output.
	jsonStr, err := extractJSONFromFencedBlock(raw)
	if err != nil {
		jsonStr, err = extractJSON(raw)
		if err != nil {
			return nil, fmt.Errorf("no JSON block found: %w", err)
		}
	}

	// Try wrapped format first
	var wrapper sourceAnalysisWrapper
	if err := json.Unmarshal([]byte(jsonStr), &wrapper); err == nil && len(wrapper.SourceAnalysis.HTTPRecords) > 0 {
		result := &wrapper.SourceAnalysis
		// Extract extensions from fenced code blocks (not from JSON)
		if codeExts := extractCodeBlockExtensions(raw); len(codeExts) > 0 {
			result.Extensions = codeExts
		}
		return result, nil
	}

	// Try direct format
	var result SourceAnalysisResult
	if err := json.Unmarshal([]byte(jsonStr), &result); err != nil {
		return nil, fmt.Errorf("failed to parse JSON: %w", err)
	}
	if len(result.HTTPRecords) == 0 {
		return nil, fmt.Errorf("no http_records found in JSON")
	}

	// If JSON had no extensions (or empty), try extracting from fenced code blocks
	if len(result.Extensions) == 0 {
		if codeExts := extractCodeBlockExtensions(raw); len(codeExts) > 0 {
			result.Extensions = codeExts
		}
	}

	return &result, nil
}

// ResolveModulesFromPlan converts agent-suggested tags and IDs into a deduplicated
// module ID list. Falls back to ["all"] when no modules are resolved.
func ResolveModulesFromPlan(tags []string, ids []string) []string {
	moduleSet := make(map[string]bool)

	if len(tags) > 0 {
		resolved := modules.ResolveModuleTags(tags)
		for _, id := range resolved {
			moduleSet[id] = true
		}
	}

	for _, id := range ids {
		moduleSet[id] = true
	}

	if len(moduleSet) == 0 {
		return []string{"all"}
	}

	result := make([]string, 0, len(moduleSet))
	for id := range moduleSet {
		result = append(result, id)
	}
	return result
}

// WriteExtensionsToTempDir writes generated JavaScript extensions to a temporary
// directory and returns the directory path. Caller is responsible for cleanup.
func WriteExtensionsToTempDir(extensions []GeneratedExtension, prefix string) (string, error) {
	dir, err := os.MkdirTemp("", prefix)
	if err != nil {
		return "", fmt.Errorf("failed to create temp dir: %w", err)
	}

	for i, ext := range extensions {
		filename := sanitizeExtensionFilename(ext.Filename, i)
		path := filepath.Join(dir, filename)
		if writeErr := os.WriteFile(path, []byte(ext.Code), 0644); writeErr != nil {
			zap.L().Warn("Failed to write extension",
				zap.String("filename", ext.Filename),
				zap.Error(writeErr))
			continue
		}
		zap.L().Info("Generated extension",
			zap.String("filename", ext.Filename),
			zap.String("reason", ext.Reason))
	}

	return dir, nil
}
