package agent

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"github.com/vigolium/vigolium/pkg/modules"
	"go.uber.org/zap"
)

// PipelinePhase identifies a phase in the multi-phase scanning pipeline.
type PipelinePhase string

const (
	PhaseSourceAnalysis PipelinePhase = "source-analysis"
	PhaseDiscover       PipelinePhase = "discover"
	PhasePlan           PipelinePhase = "plan"
	PhaseScan           PipelinePhase = "scan"
	PhaseTriage         PipelinePhase = "triage"
	PhaseRescan         PipelinePhase = "rescan"
	PhaseReport         PipelinePhase = "report"
)

// AllPipelinePhases returns the ordered list of pipeline phases.
func AllPipelinePhases() []PipelinePhase {
	return []PipelinePhase{
		PhaseSourceAnalysis, PhaseDiscover, PhasePlan, PhaseScan,
		PhaseTriage, PhaseRescan, PhaseReport,
	}
}

// AttackPlan is the structured output from the plan agent checkpoint (phase 2).
// The agent analyzes discovery results and produces a scanning strategy.
type AttackPlan struct {
	ModuleTags []string          `json:"module_tags,omitempty"`
	ModuleIDs  []string          `json:"module_ids,omitempty"`
	FocusAreas []string          `json:"focus_areas,omitempty"`
	SkipPaths  []string          `json:"skip_paths,omitempty"`
	Endpoints  []PlannedEndpoint `json:"endpoints,omitempty"`
	Notes      string            `json:"notes,omitempty"`
}

// attackPlanHasContent returns true if the plan has at least one meaningful field.
func attackPlanHasContent(plan *AttackPlan) bool {
	if plan == nil {
		return false
	}
	return len(plan.ModuleTags) > 0 ||
		len(plan.ModuleIDs) > 0 ||
		len(plan.FocusAreas) > 0 ||
		len(plan.SkipPaths) > 0 ||
		len(plan.Endpoints) > 0 ||
		plan.Notes != ""
}

// PlannedEndpoint represents a prioritized endpoint in the attack plan.
type PlannedEndpoint struct {
	URL       string   `json:"url"`
	Method    string   `json:"method,omitempty"`
	Priority  string   `json:"priority"` // high, medium, low
	Rationale string   `json:"rationale,omitempty"`
	Tags      []string `json:"tags,omitempty"`
}

// TriageResult is the structured output from the triage agent checkpoint (phase 4).
// The agent reviews findings and decides whether additional scanning is needed.
type TriageResult struct {
	Confirmed      []TriagedFinding `json:"confirmed"`
	FalsePositives []TriagedFinding `json:"false_positives"`
	FollowUps      []FollowUpScan   `json:"follow_up_scans,omitempty"`
	Verdict        string           `json:"verdict"` // "done" or "rescan"
	Notes          string           `json:"notes,omitempty"`
}

// TriagedFinding is a finding that has been reviewed by the triage agent.
type TriagedFinding struct {
	Title    string `json:"title"`
	ModuleID string `json:"module_id,omitempty"`
	URL      string `json:"url,omitempty"`
	Reason   string `json:"reason,omitempty"`
}

// FollowUpScan describes a targeted rescan recommended by the triage agent.
type FollowUpScan struct {
	URL        string   `json:"url"`
	Method     string   `json:"method,omitempty"`
	ModuleTags []string `json:"module_tags,omitempty"`
	ModuleIDs  []string `json:"module_ids,omitempty"`
	Rationale  string   `json:"rationale,omitempty"`
}

// SourceAnalysisResult is the structured output from the source analysis phase (phase 0).
// The agent explores source code and extracts routes, session config, and custom extensions.
type SourceAnalysisResult struct {
	HTTPRecords   []AgentHTTPRecord    `json:"http_records"`
	SessionConfig *AgentSessionConfig  `json:"session_config,omitempty"`
	Extensions    []GeneratedExtension `json:"extensions,omitempty"`
}

// AgentSessionConfig holds session definitions generated by the source analysis agent.
type AgentSessionConfig struct {
	Sessions []AgentSessionEntry `json:"sessions"`
}

// AgentSessionEntry represents a single session identity for authenticated scanning.
type AgentSessionEntry struct {
	Name    string            `json:"name"`
	Role    string            `json:"role"`              // "primary" or "compare"
	Headers map[string]string `json:"headers,omitempty"` // static auth headers
	Login   *AgentLoginFlow   `json:"login,omitempty"`   // login-based auth
}

// AgentLoginFlow defines a login flow discovered from source code analysis.
type AgentLoginFlow struct {
	URL         string             `json:"url"`
	Method      string             `json:"method"`
	ContentType string             `json:"content_type,omitempty"`
	Body        string             `json:"body,omitempty"`
	Extract     []AgentExtractRule `json:"extract"`
}

// AgentExtractRule defines how to extract an auth token from a login response.
type AgentExtractRule struct {
	Source  string `json:"source"`             // "cookie", "json", "header"
	Name    string `json:"name,omitempty"`     // cookie name or header name
	Path    string `json:"path,omitempty"`     // JSONPath for json source
	ApplyAs string `json:"apply_as,omitempty"` // e.g. "Authorization: Bearer {value}"
}

// GeneratedExtension represents a JavaScript extension generated by the agent.
type GeneratedExtension struct {
	Filename string `json:"filename"`
	Code     string `json:"code"`
	Reason   string `json:"reason"`
}

// sanitizeExtensionFilename ensures a filename is safe for writing to disk.
// It strips path components to prevent traversal, converts to a URL-friendly
// slug (lowercase, alphanumeric + hyphens), and falls back to a numbered
// default for empty or dot-only names.
func sanitizeExtensionFilename(name string, index int) string {
	name = filepath.Base(name)
	if name == "" || name == "." || name == ".." {
		return fmt.Sprintf("extension-%d.js", index)
	}

	// Strip .js extension for slug processing, re-add after
	ext := filepath.Ext(name)
	base := strings.TrimSuffix(name, ext)
	if ext == "" {
		ext = ".js"
	}

	// Slugify: lowercase, replace non-alphanumeric with hyphens, collapse, trim
	slug := strings.ToLower(base)
	var sb strings.Builder
	prevHyphen := false
	for _, r := range slug {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') {
			sb.WriteRune(r)
			prevHyphen = false
		} else if !prevHyphen {
			sb.WriteRune('-')
			prevHyphen = true
		}
	}
	slug = strings.Trim(sb.String(), "-")

	if slug == "" {
		return fmt.Sprintf("extension-%d.js", index)
	}
	return slug + ext
}

// QuickCheck is a declarative shorthand for simple payload-and-match scan checks.
// The swarm runner auto-generates a full JS extension from each QuickCheck.
type QuickCheck struct {
	ID       string              `json:"id"`
	Severity string              `json:"severity,omitempty"` // default: "medium"
	Scan     string              `json:"scan"`               // "per_insertion_point", "per_request", "per_host"
	Payloads []string            `json:"payloads,omitempty"` // for per_insertion_point: payloads to inject
	Requests []QuickCheckRequest `json:"requests,omitempty"` // for per_request/per_host: requests to send
	Match    QuickCheckMatch     `json:"match"`
}

// QuickCheckRequest defines a request to send in per_request/per_host quick checks.
type QuickCheckRequest struct {
	Method  string            `json:"method"`
	Path    string            `json:"path"`
	Headers map[string]string `json:"headers,omitempty"`
	Body    string            `json:"body,omitempty"`
}

// QuickCheckMatch defines match conditions for a quick check (OR logic).
type QuickCheckMatch struct {
	BodyContains   string `json:"body_contains,omitempty"`
	BodyRegex      string `json:"body_regex,omitempty"`
	Status         int    `json:"status,omitempty"`
	HeaderContains string `json:"header_contains,omitempty"`
}

// Snippet is a shorthand extension where only the scan function body is provided.
// The swarm runner wraps it in a full module scaffold with access to ctx, insertion, and vigolium.* APIs.
type Snippet struct {
	ID       string `json:"id"`
	Severity string `json:"severity,omitempty"` // default: "medium"
	Scan     string `json:"scan"`               // "per_insertion_point", "per_request", "per_host"
	Body     string `json:"body"`               // JS function body
}

// SwarmPlan is the structured output from the master agent in agent swarm mode.
// The agent analyzes the target request, selects modules, and generates custom extensions.
type SwarmPlan struct {
	ModuleTags      []string             `json:"module_tags,omitempty"`
	ModuleIDs       []string             `json:"module_ids,omitempty"`
	Extensions      []GeneratedExtension `json:"extensions,omitempty"`
	QuickChecks     []QuickCheck         `json:"quick_checks,omitempty"`
	Snippets        []Snippet            `json:"snippets,omitempty"`
	FocusAreas      []string             `json:"focus_areas,omitempty"`
	Notes           string               `json:"notes,omitempty"`
	NeedsExtensions       bool   `json:"needs_extensions,omitempty"`
	NeedsExtensionsReason string `json:"needs_extensions_reason,omitempty"`
}

// BatchProvenance tracks which batch contributed each item to a merged plan.
type BatchProvenance struct {
	ModuleTags map[string]int `json:"module_tags,omitempty"` // tag -> batch number
	ModuleIDs  map[string]int `json:"module_ids,omitempty"`  // id -> batch number
	Extensions map[string]int `json:"extensions,omitempty"`  // filename -> batch number
	FocusAreas map[string]int `json:"focus_areas,omitempty"` // focus area -> batch number
}

// TokenUsage tracks cumulative token consumption across agent calls in a run.
type TokenUsage struct {
	InputTokens  int `json:"input_tokens"`
	OutputTokens int `json:"output_tokens"`
}

// ProgressEvent reports granular progress during agent scans.
type ProgressEvent struct {
	Phase        string `json:"phase"`
	SubPhase     string `json:"sub_phase,omitempty"`
	Current      int    `json:"current,omitempty"`
	Total        int    `json:"total,omitempty"`
	FindingCount int    `json:"finding_count,omitempty"`
	Message      string `json:"message,omitempty"`
}

// SwarmResult holds the outcome of an agent swarm run.
type SwarmResult struct {
	SwarmPlan      *SwarmPlan      `json:"swarm_plan,omitempty"`
	TriageResults  []*TriageResult `json:"triage_results,omitempty"`
	TotalFindings  int             `json:"total_findings"`
	TotalRecords   int             `json:"total_records"`
	SeverityCounts map[string]int  `json:"severity_counts,omitempty"` // critical, high, medium, low, info
	Confirmed      int             `json:"confirmed"`
	FalsePositives int             `json:"false_positives"`
	Iterations     int             `json:"iterations"`
	Duration       time.Duration   `json:"duration"`
	AgentRunUUID   string          `json:"agent_run_uuid"`
	SessionID      string          `json:"session_id,omitempty"`  // last ACP session ID (for single or last batch)
	SessionIDs     []string        `json:"session_ids,omitempty"` // all ACP session IDs when batched (>5 records); nil for single-batch runs
	SessionDir      string                         `json:"session_dir,omitempty"`
	PhaseTimings    map[string]time.Duration       `json:"phase_timings,omitempty"`
	TokenUsage      TokenUsage                     `json:"token_usage,omitempty"`
	BatchProvenance *BatchProvenance               `json:"batch_provenance,omitempty"` // only set when plan was merged from multiple batches
}

// SwarmCheckpoint captures swarm pipeline state for checkpoint/resume.
type SwarmCheckpoint struct {
	CompletedPhases  []string            `json:"completed_phases"`
	TargetURL        string              `json:"target_url"`
	RecordCount      int                 `json:"record_count"`
	Plan             *SwarmPlan          `json:"plan,omitempty"`
	ExtensionDir     string              `json:"extension_dir,omitempty"`
	Timestamp        time.Time           `json:"timestamp"`
	TriageRound      int                 `json:"triage_round,omitempty"`       // last completed triage round (0-indexed)
	ExtensionRenames map[string]string   `json:"extension_renames,omitempty"`  // original filename -> renamed filename
}

// LastPhase returns the last completed phase, or "" if none.
func (cp *SwarmCheckpoint) LastPhase() string {
	if cp == nil || len(cp.CompletedPhases) == 0 {
		return ""
	}
	return cp.CompletedPhases[len(cp.CompletedPhases)-1]
}

// writeCheckpoint persists a SwarmCheckpoint to the session directory.
func writeCheckpoint(sessionDir string, cp *SwarmCheckpoint) error {
	if sessionDir == "" {
		return nil
	}
	data, err := json.MarshalIndent(cp, "", "  ")
	if err != nil {
		return fmt.Errorf("failed to marshal checkpoint: %w", err)
	}
	return os.WriteFile(filepath.Join(sessionDir, "checkpoint.json"), data, 0644)
}

// loadCheckpoint reads a SwarmCheckpoint from the session directory.
func loadCheckpoint(sessionDir string) (*SwarmCheckpoint, error) {
	data, err := os.ReadFile(filepath.Join(sessionDir, "checkpoint.json"))
	if err != nil {
		return nil, err
	}
	var cp SwarmCheckpoint
	if err := json.Unmarshal(data, &cp); err != nil {
		return nil, fmt.Errorf("failed to parse checkpoint: %w", err)
	}
	return &cp, nil
}

// swarmPlanWrapper wraps SwarmPlan for JSON parsing flexibility.
type swarmPlanWrapper struct {
	Plan SwarmPlan `json:"swarm_plan"`
}

// ParseSwarmPlan extracts a SwarmPlan from raw agent output.
// It supports two formats:
//  1. Legacy: a single JSON object containing all fields including extensions[].code
//  2. Hybrid: a single-line JSON plan (module_tags, module_ids, focus_areas, notes)
//     followed by fenced ```javascript code blocks for extensions. Each extension
//     is preceded by a heading like "#### filename.js" and optionally "Reason: ...".
//
// module_tags is optional — when absent the downstream scan runs all modules.
func ParseSwarmPlan(raw string) (*SwarmPlan, error) {
	// Try markdown section format first (most robust for LLM output)
	if plan, err := parseSwarmPlanMarkdown(raw); err == nil && swarmPlanHasContent(plan) {
		return plan, nil
	}

	// Try hybrid format: JSONL plan line + fenced code blocks for extensions
	if plan, err := parseSwarmPlanHybrid(raw); err == nil && swarmPlanHasContent(plan) {
		return plan, nil
	}

	// Try all valid JSON blocks looking for one with recognizable plan fields
	for _, block := range findAllJSONBlocks(raw) {
		if !isJSON(block) {
			continue
		}
		var wrapper swarmPlanWrapper
		if json.Unmarshal([]byte(block), &wrapper) == nil && swarmPlanHasContent(&wrapper.Plan) {
			return &wrapper.Plan, nil
		}
		var plan SwarmPlan
		if json.Unmarshal([]byte(block), &plan) == nil && swarmPlanHasContent(&plan) {
			return &plan, nil
		}
	}

	// Last resort: regex-extract fields from garbled JSON.
	if plan := extractSwarmPlanRegex(raw); plan != nil {
		zap.L().Info("Recovered swarm plan via regex fallback",
			zap.Int("module_tags", len(plan.ModuleTags)))
		return plan, nil
	}

	return nil, fmt.Errorf("failed to parse swarm plan: no recognizable plan structure found")
}

// ParseSwarmExtensions extracts extensions, quick_checks, and snippets from
// raw agent output. This is used by the Phase 2 extension agent whose only job
// is to produce code — so we don't require module_tags or other plan fields.
// Returns nil if the output contains no extensions (e.g., "No custom extensions needed.").
func ParseSwarmExtensions(raw string) (*SwarmPlan, error) {
	plan := &SwarmPlan{}

	// Extract fenced JavaScript code blocks as full extensions
	if codeExts := extractCodeBlockExtensions(raw); len(codeExts) > 0 {
		plan.Extensions = codeExts
	}

	// Extract quick_checks from fenced JSON blocks
	for _, fenced := range extractFencedBlocks(raw) {
		fenced = strings.TrimSpace(fenced)
		if fenced == "" {
			continue
		}
		// Try as quick_checks array
		if fenced[0] == '[' {
			var qcs []QuickCheck
			if json.Unmarshal([]byte(fenced), &qcs) == nil && len(qcs) > 0 && qcs[0].ID != "" {
				plan.QuickChecks = append(plan.QuickChecks, qcs...)
				continue
			}
			// Try as snippets array
			var snips []Snippet
			if json.Unmarshal([]byte(fenced), &snips) == nil && len(snips) > 0 && snips[0].ID != "" {
				plan.Snippets = append(plan.Snippets, snips...)
				continue
			}
		}
	}

	// Also try keyed JSON extraction for quick_checks
	if len(plan.QuickChecks) == 0 {
		if qcBlock := findJSONArrayInSection(raw, "quick_checks"); qcBlock != "" {
			var qcs []QuickCheck
			if json.Unmarshal([]byte(qcBlock), &qcs) == nil {
				plan.QuickChecks = qcs
			}
		}
	}

	// Check if output explicitly says no extensions needed
	lower := strings.ToLower(raw)
	if strings.Contains(lower, "no custom extensions needed") || strings.Contains(lower, "no extensions needed") {
		return nil, nil
	}

	if len(plan.Extensions) == 0 && len(plan.QuickChecks) == 0 && len(plan.Snippets) == 0 {
		return nil, fmt.Errorf("no extensions found in extension agent output")
	}

	return plan, nil
}

// swarmPlanHasContent returns true if the plan contains at least one meaningful field.
// module_tags is no longer required — a plan with only focus_areas, extensions, etc. is valid.
func swarmPlanHasContent(plan *SwarmPlan) bool {
	if plan == nil {
		return false
	}
	return len(plan.ModuleTags) > 0 ||
		len(plan.ModuleIDs) > 0 ||
		len(plan.Extensions) > 0 ||
		len(plan.QuickChecks) > 0 ||
		len(plan.Snippets) > 0 ||
		len(plan.FocusAreas) > 0 ||
		plan.Notes != ""
}

// moduleTagsRegex matches a "module_tags" JSON array in possibly garbled text.
var moduleTagsRegex = regexp.MustCompile(`"module_tags"\s*:\s*\[((?:"[^"]*"(?:\s*,\s*)?)*)\]`)

// moduleIDsRegex matches a "module_ids" JSON array in possibly garbled text.
var moduleIDsRegex = regexp.MustCompile(`"module_ids"\s*:\s*\[((?:"[^"]*"(?:\s*,\s*)?)*)\]`)

// focusAreasRegex matches a "focus_areas" JSON array.
var focusAreasRegex = regexp.MustCompile(`"focus_areas"\s*:\s*\[((?:"[^"]*"(?:\s*,\s*)?)*)\]`)

// notesRegex matches a "notes" JSON string.
var notesRegex = regexp.MustCompile(`"notes"\s*:\s*"((?:[^"\\]|\\.)*)"`)

// extractSwarmPlanRegex attempts to recover a minimal SwarmPlan from garbled JSON
// by regex-extracting individual fields. Returns nil if no recognizable fields are found.
func extractSwarmPlanRegex(raw string) *SwarmPlan {
	plan := &SwarmPlan{}

	// Try extracting module_tags (optional)
	if m := moduleTagsRegex.FindStringSubmatch(raw); len(m) >= 2 {
		var tags []string
		if json.Unmarshal([]byte("["+m[1]+"]"), &tags) == nil {
			plan.ModuleTags = tags
		}
	}

	// Try extracting module_ids (optional)
	if m := moduleIDsRegex.FindStringSubmatch(raw); len(m) >= 2 {
		var ids []string
		if json.Unmarshal([]byte("["+m[1]+"]"), &ids) == nil {
			plan.ModuleIDs = ids
		}
	}

	// Best-effort extraction of other fields
	if fm := focusAreasRegex.FindStringSubmatch(raw); len(fm) >= 2 {
		var fa []string
		if json.Unmarshal([]byte("["+fm[1]+"]"), &fa) == nil {
			plan.FocusAreas = fa
		}
	}
	if nm := notesRegex.FindStringSubmatch(raw); len(nm) >= 2 {
		plan.Notes = nm[1]
	}

	// Extract code block extensions (hybrid format)
	if codeExts := extractCodeBlockExtensions(raw); len(codeExts) > 0 {
		plan.Extensions = codeExts
	}

	if !swarmPlanHasContent(plan) {
		return nil
	}
	return plan
}

// parseSwarmPlanHybrid parses the hybrid output format where the plan JSON is a
// single line and extensions are in fenced ```javascript code blocks.
func parseSwarmPlanHybrid(raw string) (*SwarmPlan, error) {
	lines := strings.Split(raw, "\n")

	// Step 1: Find and parse the plan JSON line — look for lines containing known plan fields.
	planKeys := []string{"\"module_tags\"", "\"module_ids\"", "\"focus_areas\"", "\"extensions\"", "\"quick_checks\"", "\"snippets\""}
	var plan SwarmPlan
	planFound := false
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		hasPlanKey := false
		for _, key := range planKeys {
			if strings.Contains(line, key) {
				hasPlanKey = true
				break
			}
		}
		if !hasPlanKey {
			continue
		}
		if json.Unmarshal([]byte(line), &plan) == nil && swarmPlanHasContent(&plan) {
			planFound = true
			break
		}
		// Also try extracting JSON from this line (in case of surrounding text)
		if extracted := findJSONBlock(line); extracted != "" {
			if json.Unmarshal([]byte(extracted), &plan) == nil && swarmPlanHasContent(&plan) {
				planFound = true
				break
			}
		}
	}

	// Fallback: try all JSON blocks in the full text (handles corrupted first block + valid later block)
	if !planFound {
		for _, block := range findAllJSONBlocks(raw) {
			if json.Unmarshal([]byte(block), &plan) == nil && swarmPlanHasContent(&plan) {
				planFound = true
				break
			}
		}
	}

	if !planFound {
		return nil, fmt.Errorf("no plan JSON line found")
	}

	// Step 2: Extract fenced JavaScript code blocks as extensions (supplement, don't overwrite)
	if codeExts := extractCodeBlockExtensions(raw); len(codeExts) > 0 {
		plan.Extensions = append(plan.Extensions, codeExts...)
	}

	return &plan, nil
}

// parseSwarmPlanMarkdown parses the markdown section format where the LLM outputs
// structured sections with ## headings instead of a single JSON blob.
// This format is inherently more robust against LLM token-level corruption.
func parseSwarmPlanMarkdown(raw string) (*SwarmPlan, error) {
	sections := splitMarkdownSections(raw)

	// At least one recognized section must be present for this to be a markdown-format plan.
	recognizedSections := []string{"MODULE_TAGS", "MODULE_IDS", "FOCUS_AREAS", "NOTES", "NEEDS_EXTENSIONS"}
	hasSection := false
	for _, name := range recognizedSections {
		if _, ok := sections[name]; ok {
			hasSection = true
			break
		}
	}
	if !hasSection {
		return nil, fmt.Errorf("no recognized markdown sections found")
	}

	plan := &SwarmPlan{}

	if tagsRaw, ok := sections["MODULE_TAGS"]; ok {
		plan.ModuleTags = parseCommaSeparated(tagsRaw)
	}

	if idsRaw, ok := sections["MODULE_IDS"]; ok {
		plan.ModuleIDs = parseCommaSeparated(idsRaw)
	}

	if faRaw, ok := sections["FOCUS_AREAS"]; ok {
		plan.FocusAreas = parseBulletList(faRaw)
	}

	if notes, ok := sections["NOTES"]; ok {
		plan.Notes = strings.TrimSpace(notes)
	}

	if ne, ok := sections["NEEDS_EXTENSIONS"]; ok {
		cleaned := strings.TrimSpace(stripCodeFenceMarkers(ne))
		lines := strings.SplitN(cleaned, "\n", 2)

		// Try labeled format first: "conclusion: yes" / "reason: ..."
		if conclusionVal, ok := extractLabeledValue(lines[0], "conclusion"); ok {
			decision := strings.ToLower(conclusionVal)
			plan.NeedsExtensions = decision == "yes" || decision == "true"
			if len(lines) > 1 {
				if reasonVal, ok := extractLabeledValue(lines[1], "reason"); ok {
					plan.NeedsExtensionsReason = reasonVal
				} else {
					plan.NeedsExtensionsReason = strings.TrimSpace(lines[1])
				}
			}
		} else {
			// Legacy plain format: first line is yes/no, second line is reason
			decision := strings.TrimSpace(strings.ToLower(lines[0]))
			plan.NeedsExtensions = decision == "yes" || decision == "true"
			if len(lines) > 1 {
				plan.NeedsExtensionsReason = strings.TrimSpace(lines[1])
			}
		}
	}

	// Extract extensions from fenced code blocks (existing logic handles #### headings)
	if codeExts := extractCodeBlockExtensions(raw); len(codeExts) > 0 {
		plan.Extensions = codeExts
	}

	// Extract quick_checks from JSON — try keyed field first, then standalone arrays in fences
	if qcBlock := findJSONArrayInSection(raw, "quick_checks"); qcBlock != "" {
		var qcs []QuickCheck
		if json.Unmarshal([]byte(qcBlock), &qcs) == nil {
			plan.QuickChecks = qcs
		}
	}
	if len(plan.QuickChecks) == 0 {
		// Try fenced JSON blocks as standalone quick check arrays
		for _, fenced := range extractFencedBlocks(raw) {
			fenced = strings.TrimSpace(fenced)
			if fenced == "" || fenced[0] != '[' {
				continue
			}
			var qcs []QuickCheck
			if json.Unmarshal([]byte(fenced), &qcs) == nil && len(qcs) > 0 && qcs[0].ID != "" {
				plan.QuickChecks = qcs
				break
			}
		}
	}

	return plan, nil
}

// splitMarkdownSections splits text by ## headings and returns a map of section name to content.
func splitMarkdownSections(raw string) map[string]string {
	sections := make(map[string]string)
	lines := strings.Split(raw, "\n")

	var currentSection string
	var content strings.Builder

	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "## ") && !strings.HasPrefix(trimmed, "### ") {
			// Save previous section
			if currentSection != "" {
				sections[currentSection] = content.String()
			}
			currentSection = strings.TrimSpace(trimmed[3:])
			content.Reset()
			continue
		}
		if currentSection != "" {
			if content.Len() > 0 {
				content.WriteByte('\n')
			}
			content.WriteString(line)
		}
	}
	// Save last section
	if currentSection != "" {
		sections[currentSection] = content.String()
	}
	return sections
}

// parseCommaSeparated splits a string by commas and/or newlines and returns trimmed,
// non-empty tokens. It also strips code fence markers (```) which LLMs sometimes
// wrap around values in markdown sections.
func parseCommaSeparated(s string) []string {
	// Strip code fence markers (``` or ```lang) — agents sometimes wrap values in fences
	s = stripCodeFenceMarkers(s)

	var result []string
	// Split by commas first; if that yields only one token containing newlines,
	// fall back to newline splitting (agents sometimes use newline-separated lists).
	commaParts := strings.Split(s, ",")
	if len(commaParts) == 1 && strings.Contains(s, "\n") {
		// Newline-separated list
		for _, line := range strings.Split(s, "\n") {
			line = strings.TrimSpace(line)
			if line != "" {
				result = append(result, line)
			}
		}
	} else {
		for _, token := range commaParts {
			token = strings.TrimSpace(token)
			if token != "" {
				result = append(result, token)
			}
		}
	}
	return result
}

// stripCodeFenceMarkers removes ``` lines (with optional language tag) from a string.
func stripCodeFenceMarkers(s string) string {
	var out strings.Builder
	for _, line := range strings.Split(s, "\n") {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "```") {
			continue
		}
		if out.Len() > 0 {
			out.WriteByte('\n')
		}
		out.WriteString(line)
	}
	return out.String()
}

// extractLabeledValue checks if a line has the form "label: value" and returns the value.
func extractLabeledValue(line, label string) (string, bool) {
	trimmed := strings.TrimSpace(line)
	prefix := label + ":"
	if len(trimmed) >= len(prefix) && strings.EqualFold(trimmed[:len(prefix)], prefix) {
		return strings.TrimSpace(trimmed[len(prefix):]), true
	}
	return "", false
}

// parseBulletList extracts items from a bulleted markdown list.
func parseBulletList(s string) []string {
	var result []string
	for _, line := range strings.Split(s, "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "- ") {
			item := strings.TrimSpace(line[2:])
			if item != "" {
				result = append(result, item)
			}
		} else if strings.HasPrefix(line, "* ") {
			item := strings.TrimSpace(line[2:])
			if item != "" {
				result = append(result, item)
			}
		} else if line != "" {
			// Plain text line (not bulleted)
			result = append(result, line)
		}
	}
	return result
}

// findJSONArrayInSection searches for a JSON array associated with a key name in the raw text.
func findJSONArrayInSection(raw, key string) string {
	pattern := `"` + key + `"`
	idx := strings.Index(raw, pattern)
	if idx < 0 {
		return ""
	}
	// Find the '[' after the key
	rest := raw[idx+len(pattern):]
	for i, ch := range rest {
		if ch == '[' {
			block := findJSONBlockFrom(rest, i)
			if block != "" {
				return block
			}
		}
		if ch != ':' && ch != ' ' && ch != '\t' {
			break
		}
	}
	return ""
}

// extractCodeBlockExtensions extracts GeneratedExtension entries from fenced
// ```javascript code blocks in the raw output. It looks for heading patterns
// like "#### filename.js" or "### filename.js" before each block, and
// "Reason: ..." lines for the reason field.
func extractCodeBlockExtensions(raw string) []GeneratedExtension {
	var extensions []GeneratedExtension
	unnamedCounter := 0
	lines := strings.Split(raw, "\n")

	for i := 0; i < len(lines); i++ {
		trimmed := strings.TrimSpace(lines[i])

		// Look for opening fence: ```javascript or ```js
		if !isJSFenceOpen(trimmed) {
			continue
		}

		fenceLineIdx := i

		// Collect code until closing ```
		var code strings.Builder
		i++
		for i < len(lines) {
			if strings.TrimSpace(lines[i]) == "```" {
				break
			}
			if code.Len() > 0 {
				code.WriteByte('\n')
			}
			code.WriteString(lines[i])
			i++
		}

		codeStr := code.String()
		if codeStr == "" {
			continue
		}

		// Extract filename from a preceding heading (#### filename.js / ### filename.js)
		// and reason from a "Reason: ..." line. Scan backwards from the fence line.
		filename, reason := extractExtensionMeta(lines, fenceLineIdx)

		// If no heading filename, try to extract from module id in the code
		if filename == "" {
			filename = extractFilenameFromCode(codeStr)
		}
		if filename == "extension.js" {
			filename = fmt.Sprintf("extension-%d.js", unnamedCounter)
			unnamedCounter++
		}

		extensions = append(extensions, GeneratedExtension{
			Filename: filename,
			Code:     codeStr,
			Reason:   reason,
		})
	}

	return extensions
}

// isJSFenceOpen returns true if the line opens a JavaScript code fence.
func isJSFenceOpen(line string) bool {
	if strings.HasPrefix(line, "```javascript") {
		return true
	}
	// Match ```js but not ```json
	if strings.HasPrefix(line, "```js") && !strings.HasPrefix(line, "```json") {
		return true
	}
	return false
}

// extractExtensionMeta scans lines backwards from fenceIdx to find a heading
// containing a .js filename and an optional "Reason:" line.
func extractExtensionMeta(lines []string, fenceIdx int) (filename, reason string) {
	// Scan up to 5 lines backwards looking for metadata
	start := fenceIdx - 5
	if start < 0 {
		start = 0
	}
	for j := fenceIdx; j >= start; j-- {
		line := strings.TrimSpace(lines[j])

		// Heading with filename: "#### custom-check.js" or "### custom-check.js"
		if filename == "" && strings.HasPrefix(line, "#") {
			// Strip leading # characters and whitespace
			name := strings.TrimLeft(line, "# ")
			if strings.HasSuffix(name, ".js") {
				filename = name
			}
		}

		// Reason line
		if reason == "" && strings.HasPrefix(line, "Reason:") {
			reason = strings.TrimSpace(strings.TrimPrefix(line, "Reason:"))
		}
	}
	return filename, reason
}

// extractFilenameFromCode tries to extract a filename from the module id in JS code.
// It looks for patterns like id: "custom-something" and converts to custom-something.js.
func extractFilenameFromCode(code string) string {
	// Look for id: "..." or id: '...'
	for _, pattern := range []string{`id: "`, `id: '`, `id:"`, `id:'`} {
		idx := strings.Index(code, pattern)
		if idx < 0 {
			continue
		}
		start := idx + len(pattern)
		quote := code[start-1] // matching quote character
		end := strings.IndexByte(code[start:], quote)
		if end > 0 {
			return code[start:start+end] + ".js"
		}
	}
	return "extension.js"
}

// SourceAnalysisConfig configures a source analysis run. Used by both pipeline and swarm.
type SourceAnalysisConfig struct {
	AgentName      string
	AgentACPCmd    string // ad-hoc ACP command override (e.g. "traecli acp")
	TargetURL      string
	SourcePath     string
	Files          []string
	Instruction    string // user-provided custom instruction appended to the prompt
	PromptTemplate string // override template ID (default: "pipeline-source-analysis")
	SessionKey     string // pool session key override (prevents context accumulation across phases)
	DryRun         bool
	ShowPrompt     bool // print rendered prompt to stderr before executing
	ScanUUID       string
	ProjectUUID    string
	StreamWriter   io.Writer
}

// RepairHTTPRecordsWithLLM attempts to fix garbled HTTP records output by sending
// the raw text to the configured LLM agent with a repair prompt. The repaired output
// is re-parsed through the JSONL + garbled recovery pipeline.
func RepairHTTPRecordsWithLLM(ctx context.Context, engine *Engine, rawOutput string, cfg repairConfig) []AgentHTTPRecord {
	if engine == nil || rawOutput == "" {
		return nil
	}

	// Truncate to 32KB to fit context
	const maxRepairBytes = 32 * 1024
	if len(rawOutput) > maxRepairBytes {
		rawOutput = rawOutput[:maxRepairBytes]
	}

	prompt := buildHTTPRecordRepairPrompt(rawOutput)

	result, err := engine.Run(ctx, Options{
		AgentName:    cfg.AgentName,
		AgentACPCmd:  cfg.AgentACPCmd,
		PromptInline: prompt,
		ShowPrompt:   cfg.ShowPrompt,
		SessionKey:   "json-repair",
	})
	if err != nil {
		zap.L().Warn("LLM repair for HTTP records failed", zap.Error(err))
		return nil
	}

	output := result.RawOutput

	// Try JSONL from ```jsonl block first
	if jsonlContent, err := extractJSONLFromFencedBlock(output); err == nil {
		records, _ := parseHTTPRecordJSONL(jsonlContent)
		if len(records) > 0 {
			zap.L().Info("LLM repair recovered HTTP records via JSONL",
				zap.Int("count", len(records)))
			return records
		}
	}

	// Try standard JSON parsing
	records, parseErr := ParseHTTPRecords(output)
	if parseErr == nil && len(records) > 0 {
		zap.L().Info("LLM repair recovered HTTP records via JSON",
			zap.Int("count", len(records)))
		return records
	}

	// Try garbled recovery on the repaired output
	records, _ = extractRecordsFromGarbled(output)
	if len(records) > 0 {
		zap.L().Info("LLM repair recovered HTTP records via garbled extraction",
			zap.Int("count", len(records)))
		return records
	}

	zap.L().Warn("LLM repair produced no parseable HTTP records")
	return nil
}

// buildHTTPRecordRepairPrompt constructs the prompt for the HTTP record repair LLM call.
func buildHTTPRecordRepairPrompt(rawOutput string) string {
	var sb strings.Builder
	sb.WriteString("The following output was supposed to contain HTTP records (routes extracted from source code) but has JSON syntax errors.\n")
	sb.WriteString("Fix the JSON errors and return the records as JSONL (one JSON object per line) in a ```jsonl fenced code block.\n")
	sb.WriteString("Each line must be a valid JSON object like: {\"method\":\"GET\",\"url\":\"http://...\",\"headers\":{},\"body\":\"\",\"notes\":\"...\"}\n")
	sb.WriteString("Do NOT change the data — only fix syntax errors. Do NOT add explanations outside the code block.\n\n")
	sb.WriteString("## Garbled Output\n\n")
	sb.WriteString("```\n")
	sb.WriteString(rawOutput)
	sb.WriteString("\n```\n")
	return sb.String()
}

// EnsureSessionDir creates the session directory for a given run ID under the specified base directory.
// If baseDir is empty, defaults to ~/.vigolium/agent-sessions/.
// Returns the absolute path to the created directory.
func EnsureSessionDir(baseDir, runID string) (string, error) {
	if baseDir == "" {
		home, err := os.UserHomeDir()
		if err != nil {
			return "", fmt.Errorf("failed to get home dir: %w", err)
		}
		baseDir = filepath.Join(home, ".vigolium", "agent-sessions")
	}
	dir := filepath.Join(baseDir, runID)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return "", fmt.Errorf("failed to create session dir: %w", err)
	}
	return dir, nil
}

// WriteExtensionsToSessionDir writes generated JavaScript extensions to <sessionDir>/extensions/
// and returns the extensions subdirectory path.
func WriteExtensionsToSessionDir(extensions []GeneratedExtension, sessionDir string) (string, error) {
	extDir := filepath.Join(sessionDir, "extensions")
	if err := os.MkdirAll(extDir, 0755); err != nil {
		return "", fmt.Errorf("failed to create extensions dir: %w", err)
	}
	for i, ext := range extensions {
		filename := sanitizeExtensionFilename(ext.Filename, i)
		path := filepath.Join(extDir, filename)
		if writeErr := os.WriteFile(path, []byte(ext.Code), 0644); writeErr != nil {
			zap.L().Warn("Failed to write extension",
				zap.String("filename", ext.Filename), zap.Error(writeErr))
			continue
		}
		zap.L().Info("Generated extension",
			zap.String("filename", ext.Filename),
			zap.String("reason", ext.Reason),
			zap.String("path", path))
	}
	return extDir, nil
}

// ScanRequest encapsulates parameters for a scan callback invocation.
// This unified type is shared by both Pipeline and Swarm modes.
type ScanRequest struct {
	ModuleTags   []string // module tags from the agent's plan
	ModuleIDs    []string // explicit module IDs from the agent's plan
	ExtensionDir string   // path to generated JS extensions (empty if none)
	IsRescan     bool     // true for triage-driven targeted rescans
}

// ScanFunc is the unified callback signature for running scans.
// Both Pipeline and Swarm modes use this type for their scan callbacks.
type ScanFunc func(ctx context.Context, req ScanRequest) error

// PipelineConfig configures a pipeline run.
type PipelineConfig struct {
	TargetURL       string
	AgentName       string
	AgentACPCmd     string // ad-hoc ACP command override (e.g. "traecli acp")
	Focus           string
	Instruction     string // user-provided custom instruction appended to agent prompts
	SourcePath      string
	Files           []string
	MaxRescanRounds int
	SkipPhases      map[PipelinePhase]bool
	StartFrom       PipelinePhase
	DryRun          bool
	ShowPrompt      bool // print rendered prompts to stderr before executing
	StreamWriter    io.Writer
	ProjectUUID     string
	ScanUUID        string

	// DiscoverFunc runs the discovery phase (deparos + spidering).
	// It should populate the database with HTTP records.
	DiscoverFunc func(ctx context.Context) error

	// ScanFunc runs the audit phase with the given module filters.
	ScanFunc ScanFunc

	// PhaseCallback is called when a pipeline phase starts.
	// Used by the API server to emit SSE phase events and update status.
	PhaseCallback func(phase PipelinePhase)

	// SourceAnalysisCallback is called after Phase 0 completes to allow the caller
	// to process generated extensions and session config (e.g. write to disk).
	SourceAnalysisCallback func(result *SourceAnalysisResult) error
}

// PipelineResult holds the outcome of a full pipeline run.
type PipelineResult struct {
	SourceAnalysis *SourceAnalysisResult `json:"source_analysis,omitempty"`
	Plan           *AttackPlan           `json:"plan,omitempty"`
	TriageResults  []*TriageResult       `json:"triage_results,omitempty"`
	TotalFindings  int                   `json:"total_findings"`
	Confirmed      int                   `json:"confirmed"`
	FalsePositives int                   `json:"false_positives"`
	RescanRounds   int                   `json:"rescan_rounds"`
	PhasesRun      []PipelinePhase                `json:"phases_run"`
	PhaseTimings   map[PipelinePhase]time.Duration `json:"phase_timings,omitempty"`
	Duration       time.Duration                  `json:"duration"`
	SessionID      string                         `json:"session_id,omitempty"` // ACP session ID for resume
	TokenUsage     TokenUsage                     `json:"token_usage,omitempty"`
}

// attackPlanWrapper wraps AttackPlan for JSON parsing flexibility.
type attackPlanWrapper struct {
	Plan AttackPlan `json:"plan"`
}

// triageResultWrapper wraps TriageResult for JSON parsing flexibility.
type triageResultWrapper struct {
	Triage TriageResult `json:"triage"`
}

// sourceAnalysisWrapper wraps SourceAnalysisResult for JSON parsing flexibility.
type sourceAnalysisWrapper struct {
	SourceAnalysis SourceAnalysisResult `json:"source_analysis"`
}

// ParseAttackPlan extracts an AttackPlan from raw agent output.
func ParseAttackPlan(raw string) (*AttackPlan, error) {
	jsonStr, err := extractJSON(raw)
	if err != nil {
		return nil, fmt.Errorf("failed to extract JSON from agent output: %w", err)
	}

	// Try wrapped format: {"plan": {...}}
	var wrapper attackPlanWrapper
	if err := json.Unmarshal([]byte(jsonStr), &wrapper); err == nil && attackPlanHasContent(&wrapper.Plan) {
		return &wrapper.Plan, nil
	}

	// Try direct format: {...}
	var plan AttackPlan
	if err := json.Unmarshal([]byte(jsonStr), &plan); err == nil && attackPlanHasContent(&plan) {
		return &plan, nil
	}

	return nil, fmt.Errorf("failed to parse attack plan from JSON: no recognizable plan structure found")
}

// ParseTriageResult extracts a TriageResult from raw agent output.
func ParseTriageResult(raw string) (*TriageResult, error) {
	jsonStr, err := extractJSON(raw)
	if err != nil {
		return nil, fmt.Errorf("failed to extract JSON from agent output: %w", err)
	}

	// Try wrapped format: {"triage": {...}}
	var wrapper triageResultWrapper
	if err := json.Unmarshal([]byte(jsonStr), &wrapper); err == nil && wrapper.Triage.Verdict != "" {
		return &wrapper.Triage, nil
	}

	// Try direct format: {...}
	var result TriageResult
	if err := json.Unmarshal([]byte(jsonStr), &result); err == nil && result.Verdict != "" {
		return &result, nil
	}

	return nil, fmt.Errorf("failed to parse triage result from JSON: invalid structure (expected verdict)")
}

// ParseSourceAnalysisResult extracts a SourceAnalysisResult from raw agent output.
// It uses a layered strategy to maximize recovery from malformed LLM output:
//  1. JSONL: Parse records from a ```jsonl fenced block (one JSON object per line — blast-radius reduction)
//  2. Hybrid: JSON object with http_records/session_config + fenced ```javascript code blocks
//  3. Multi-block merge: Merge http_records across multiple ```json blocks
//  4. Legacy: Single JSON object containing all fields
//  5. Garbled recovery: Scan raw text for individual {"method":...} objects
//  6. Session-config-only: Return session_config when present without routes (auth sub-agent)
//  7. Extensions-only fallback: Return any ```javascript code blocks even when no records parse
func ParseSourceAnalysisResult(raw string) (*SourceAnalysisResult, error) {
	// Lazily extract code block extensions — only computed once, on first access.
	// Agent output frequently contains ```javascript fenced blocks for extensions
	// alongside JSON blocks for records/session_config. Extracting and merging them
	// ensures they are never lost regardless of which JSON parsing path succeeds.
	var codeExts []GeneratedExtension
	codeExtsLoaded := false
	getCodeExts := func() []GeneratedExtension {
		if !codeExtsLoaded {
			codeExts = extractCodeBlockExtensions(raw)
			codeExtsLoaded = true
		}
		return codeExts
	}

	mergeCodeExts := func(result *SourceAnalysisResult) {
		if exts := getCodeExts(); len(exts) > 0 {
			result.Extensions = mergeExtensionsByFilename(result.Extensions, exts)
		}
	}

	// Strategy 1: Try JSONL from ```jsonl fenced block (blast-radius reduction for large route lists)
	if jsonlContent, err := extractJSONLFromFencedBlock(raw); err == nil {
		records, badCount := parseHTTPRecordJSONL(jsonlContent)
		if len(records) > 0 {
			if badCount > 0 {
				zap.L().Warn("JSONL parsing: skipped malformed lines",
					zap.Int("good", len(records)),
					zap.Int("bad", badCount))
			}
			result := &SourceAnalysisResult{HTTPRecords: records}
			// Also extract session_config from any ```json block in the same output
			result.SessionConfig = extractSessionConfigFromGarbled(raw)
			mergeCodeExts(result)
			return result, nil
		}
	}

	// Strategy 2: Try hybrid format — JSON with records/session_config + fenced code blocks for extensions
	if result, err := parseSourceAnalysisHybrid(raw); err == nil && len(result.HTTPRecords) > 0 {
		mergeCodeExts(result)
		return result, nil
	}

	// Strategy 3: Try multi-block merge — when agent outputs multiple JSON blocks (e.g., separate tasks),
	// merge http_records from all parseable blocks into a single result.
	if result := mergeMultiBlockSourceAnalysis(raw); result != nil && len(result.HTTPRecords) > 0 {
		mergeCodeExts(result)
		return result, nil
	}

	// Strategy 4: Fall back to legacy all-in-one JSON format
	jsonStr, jsonErr := extractJSON(raw)
	if jsonErr == nil {
		// Try wrapped format: {"source_analysis": {...}}
		var wrapper sourceAnalysisWrapper
		if err := json.Unmarshal([]byte(jsonStr), &wrapper); err == nil && len(wrapper.SourceAnalysis.HTTPRecords) > 0 {
			result := &wrapper.SourceAnalysis
			mergeCodeExts(result)
			return result, nil
		}

		// Try direct format: {...}
		var result SourceAnalysisResult
		if err := json.Unmarshal([]byte(jsonStr), &result); err == nil {
			mergeCodeExts(&result)
			if len(result.HTTPRecords) > 0 {
				return &result, nil
			}
		} else {
			// Array-of-records fallback: the LLM sometimes outputs a bare JSON array
			var records []AgentHTTPRecord
			if arrErr := json.Unmarshal([]byte(jsonStr), &records); arrErr == nil && len(records) > 0 {
				res := &SourceAnalysisResult{HTTPRecords: records}
				mergeCodeExts(res)
				return res, nil
			}
		}
	}

	// Strategy 5: Garbled recovery — scan raw text for individual {"method":...} objects
	if strings.Contains(raw, `"method"`) {
		records, failCount := extractRecordsFromGarbled(raw)
		if len(records) > 0 {
			zap.L().Warn("Recovered HTTP records from garbled output",
				zap.Int("recovered", len(records)),
				zap.Int("failed", failCount))
			result := &SourceAnalysisResult{HTTPRecords: records}
			result.SessionConfig = extractSessionConfigFromGarbled(raw)
			mergeCodeExts(result)
			return result, nil
		}
	}

	// Strategy 6: Session-config-only fallback — the auth sub-agent legitimately returns
	// empty http_records with a valid session_config. Extract it so it's not lost.
	if sessionCfg := extractSessionConfigFromGarbled(raw); sessionCfg != nil && len(sessionCfg.Sessions) > 0 {
		result := &SourceAnalysisResult{SessionConfig: sessionCfg}
		mergeCodeExts(result)
		return result, nil
	}

	// Strategy 7: Extensions-only fallback — return JS code blocks even when no records parse
	if exts := getCodeExts(); len(exts) > 0 {
		return &SourceAnalysisResult{Extensions: exts}, nil
	}

	if jsonErr != nil {
		return nil, fmt.Errorf("failed to extract JSON from agent output: %w", jsonErr)
	}
	return nil, fmt.Errorf("failed to parse source analysis result: no http_records found")
}

// extractSessionConfigFromJSON scans all ```json fenced blocks for session_config data.
// Returns the first valid session_config found, or nil if none.
func extractSessionConfigFromJSON(raw string) *AgentSessionConfig {
	blocks := extractAllJSONFromFencedBlocks(raw)
	for _, block := range blocks {
		var sa SourceAnalysisResult
		if err := json.Unmarshal([]byte(block), &sa); err == nil && sa.SessionConfig != nil && len(sa.SessionConfig.Sessions) > 0 {
			return sa.SessionConfig
		}
		// Try wrapper format too
		var wrapper sourceAnalysisWrapper
		if err := json.Unmarshal([]byte(block), &wrapper); err == nil && wrapper.SourceAnalysis.SessionConfig != nil {
			return wrapper.SourceAnalysis.SessionConfig
		}
	}
	return nil
}

// extractSessionConfigFromGarbled recovers session config from garbled agent output.
// It uses a layered approach: clean extraction first, then needle-based scanning
// for "session_config", "sessions", and individual "login" objects.
func extractSessionConfigFromGarbled(raw string) *AgentSessionConfig {
	// Layer 1: delegate to clean path — zero overhead for well-formed output
	if cfg := extractSessionConfigFromJSON(raw); cfg != nil {
		return cfg
	}

	// Layer 2: scan for "session_config" needle, extract enclosing JSON block
	if idx := strings.Index(raw, `"session_config"`); idx >= 0 {
		// Walk backward to find the opening { for the enclosing object
		start := idx - 1
		for start >= 0 && raw[start] != '{' {
			start--
		}
		if start >= 0 {
			block := findJSONBlockFrom(raw, start)
			if block != "" {
				// Try as SourceAnalysisResult
				var sa SourceAnalysisResult
				if err := json.Unmarshal([]byte(block), &sa); err == nil && sa.SessionConfig != nil && len(sa.SessionConfig.Sessions) > 0 {
					return sa.SessionConfig
				}
				// Try as bare AgentSessionConfig
				var cfg AgentSessionConfig
				if err := json.Unmarshal([]byte(block), &cfg); err == nil && len(cfg.Sessions) > 0 {
					return &cfg
				}
			}
		}
	}

	// Layer 3: scan for "sessions" needle with enclosing object
	if idx := strings.Index(raw, `"sessions"`); idx >= 0 {
		start := idx - 1
		for start >= 0 && raw[start] != '{' {
			start--
		}
		if start >= 0 {
			block := findJSONBlockFrom(raw, start)
			if block != "" {
				var cfg AgentSessionConfig
				if err := json.Unmarshal([]byte(block), &cfg); err == nil && len(cfg.Sessions) > 0 {
					return &cfg
				}
			}
		}
	}

	// Layer 4: scan for individual "login" objects containing "url" — JSON unmarshal
	needle := `"login"`
	var entries []AgentSessionEntry
	i := 0
	for i < len(raw) {
		idx := strings.Index(raw[i:], needle)
		if idx < 0 {
			break
		}
		pos := i + idx

		// Walk backward to find the opening { for the session entry
		start := pos - 1
		for start >= 0 && raw[start] != '{' {
			start--
		}
		if start < 0 {
			i = pos + len(needle)
			continue
		}

		block := findJSONBlockFrom(raw, start)
		if block == "" {
			i = pos + len(needle)
			continue
		}

		var entry AgentSessionEntry
		if err := json.Unmarshal([]byte(block), &entry); err == nil && entry.Name != "" {
			entries = append(entries, entry)
		}

		i = start + len(block)
	}

	if len(entries) > 0 {
		return &AgentSessionConfig{Sessions: entries}
	}

	// Layer 5: regex-based field extraction for deeply garbled JSON.
	// When field keys/values are interleaved by LLM streaming, JSON is structurally
	// broken but individual field values are often intact. Extract them with regexes.
	if cfg := extractSessionConfigFromRegex(raw); cfg != nil {
		return cfg
	}

	return nil
}

// sessionNameRe matches "name": "value" patterns in garbled JSON.
var sessionNameRe = regexp.MustCompile(`"name"\s*:\s*"([^"]+)"`)

// sessionRoleRe matches "role": "value" patterns.
var sessionRoleRe = regexp.MustCompile(`"role"\s*:\s*"([^"]+)"`)

// loginURLRe matches "url": "http..." patterns inside login objects.
var loginURLRe = regexp.MustCompile(`"url"\s*:\s*"(https?://[^"]+)"`)

// loginMethodRe matches "method": "POST" etc.
var loginMethodRe = regexp.MustCompile(`"method"\s*:\s*"([A-Z]+)"`)

// loginBodyRe matches "body": "..." patterns (handles escaped quotes).
var loginBodyRe = regexp.MustCompile(`"body"\s*:\s*"((?:[^"\\]|\\.)*)"`)

// loginContentTypeRe matches content_type values (may have garbled key).
var loginContentTypeRe = regexp.MustCompile(`content_type[^"]*"\s*:\s*"(application/[^"]+)"`)

// extractSessionConfigFromRegex recovers session config from deeply garbled JSON
// by scanning for individual field values with regexes. It splits the text around
// session "name" anchors and extracts login details from each region.
func extractSessionConfigFromRegex(raw string) *AgentSessionConfig {
	// Find all session name matches — these are our anchors for splitting regions
	nameMatches := sessionNameRe.FindAllStringIndex(raw, -1)
	if len(nameMatches) == 0 {
		return nil
	}

	// Check that this is actually session config context (not unrelated "name" fields)
	if !strings.Contains(raw, `"login"`) && !strings.Contains(raw, `"sessions"`) && !strings.Contains(raw, `"session_config"`) {
		return nil
	}

	var entries []AgentSessionEntry

	for idx, nameLoc := range nameMatches {
		// Extract the region for this session entry: from this name match to the next one (or end)
		regionStart := nameLoc[0]
		regionEnd := len(raw)
		if idx+1 < len(nameMatches) {
			regionEnd = nameMatches[idx+1][0]
		}
		region := raw[regionStart:regionEnd]

		// Extract name
		nameSubmatch := sessionNameRe.FindStringSubmatch(region)
		if nameSubmatch == nil {
			continue
		}
		name := nameSubmatch[1]

		// Skip names that don't look like session identifiers
		if len(name) > 50 || strings.ContainsAny(name, "{}[]") {
			continue
		}

		entry := AgentSessionEntry{Name: name}

		// Extract role
		if m := sessionRoleRe.FindStringSubmatch(region); m != nil {
			entry.Role = m[1]
		}

		// Extract login flow
		if urlMatch := loginURLRe.FindStringSubmatch(region); urlMatch != nil {
			login := &AgentLoginFlow{
				URL: urlMatch[1],
			}
			if m := loginMethodRe.FindStringSubmatch(region); m != nil {
				login.Method = m[1]
			} else {
				login.Method = "POST" // login flows are almost always POST
			}
			if m := loginContentTypeRe.FindStringSubmatch(region); m != nil {
				login.ContentType = m[1]
			}
			if m := loginBodyRe.FindStringSubmatch(region); m != nil {
				login.Body = m[1]
			}
			entry.Login = login
		}

		entries = append(entries, entry)
	}

	if len(entries) > 0 {
		return &AgentSessionConfig{Sessions: entries}
	}
	return nil
}

// sessionConfigNeedsRepair determines whether LLM repair should be attempted for session config.
// Two cases trigger repair:
//   - Case A: No session config recovered at all, but raw output contains session keywords
//   - Case B: Session config recovered (e.g. via regex Layer 5) but ALL login flows lack
//     extract rules AND the raw output contains "extract" — meaning extract rules were
//     present but lost during garbled recovery
func sessionConfigNeedsRepair(cfg *AgentSessionConfig, rawOutput string) bool {
	// Case A: no config at all, but raw output has session-related keywords
	if cfg == nil || len(cfg.Sessions) == 0 {
		hasSessionKeywords := strings.Contains(rawOutput, `"session_config"`) ||
			strings.Contains(rawOutput, `"sessions"`) ||
			(strings.Contains(rawOutput, `"login"`) && strings.Contains(rawOutput, `"url"`))
		return hasSessionKeywords
	}

	// Case B: config recovered but all login flows lost extract rules
	if !strings.Contains(rawOutput, `"extract"`) {
		return false // no extract rules in raw output — nothing was lost
	}
	for _, s := range cfg.Sessions {
		if s.Login != nil && len(s.Login.Extract) > 0 {
			return false // at least one flow has extract rules — no repair needed
		}
	}
	// All login flows lack extract rules but raw output had them
	return true
}

// RepairSessionConfigWithLLM attempts to fix garbled session config output by sending
// the raw text to the configured LLM agent with a repair prompt. The repaired output
// is re-parsed through extractSessionConfigFromGarbled().
func RepairSessionConfigWithLLM(ctx context.Context, engine *Engine, rawOutput string, cfg repairConfig) *AgentSessionConfig {
	if engine == nil || rawOutput == "" {
		return nil
	}

	// Truncate to 32KB to fit context
	const maxRepairBytes = 32 * 1024
	if len(rawOutput) > maxRepairBytes {
		rawOutput = rawOutput[:maxRepairBytes]
	}

	prompt := buildSessionConfigRepairPrompt(rawOutput)

	result, err := engine.Run(ctx, Options{
		AgentName:    cfg.AgentName,
		AgentACPCmd:  cfg.AgentACPCmd,
		PromptInline: prompt,
		ShowPrompt:   cfg.ShowPrompt,
		SessionKey:   "json-repair",
	})
	if err != nil {
		zap.L().Warn("LLM repair for session config failed", zap.Error(err))
		return nil
	}

	repaired := extractSessionConfigFromGarbled(result.RawOutput)
	if repaired != nil && len(repaired.Sessions) > 0 {
		zap.L().Info("LLM repair recovered session config",
			zap.Int("sessions", len(repaired.Sessions)))
		return repaired
	}

	zap.L().Warn("LLM repair produced no parseable session config")
	return nil
}

// buildSessionConfigRepairPrompt constructs the prompt for the session config repair LLM call.
func buildSessionConfigRepairPrompt(rawOutput string) string {
	var sb strings.Builder
	sb.WriteString("The following output was supposed to contain session configuration for authenticated scanning but has JSON syntax errors.\n")
	sb.WriteString("Fix the JSON errors and return a valid JSON object in a ```json fenced code block.\n")
	sb.WriteString("Do NOT change the data — only fix syntax errors. Do NOT add explanations outside the code block.\n\n")
	sb.WriteString("## Expected Schema\n\n")
	sb.WriteString("```json\n")
	sb.WriteString(`{
  "sessions": [
    {
      "name": "session-name",
      "role": "primary",
      "login": {
        "url": "http://example.com/api/login",
        "method": "POST",
        "content_type": "application/json",
        "body": "{\"username\":\"admin\",\"password\":\"admin\"}",
        "extract": [
          {
            "source": "json",
            "path": "$.token",
            "apply_as": "Authorization: Bearer {value}"
          }
        ]
      }
    }
  ]
}`)
	sb.WriteString("\n```\n\n")
	sb.WriteString("CRITICAL: The `extract` rules are essential — they define how auth tokens are extracted from login responses. Do NOT omit them.\n\n")
	sb.WriteString("## Garbled Output\n\n")
	sb.WriteString("```\n")
	sb.WriteString(rawOutput)
	sb.WriteString("\n```\n")
	return sb.String()
}

// mergeExtensionsByFilename merges two extension slices, deduplicating by filename.
// Extensions from the second slice (codeExts) take precedence on filename collisions
// since fenced code blocks are the canonical source for extension code.
func mergeExtensionsByFilename(existing, codeExts []GeneratedExtension) []GeneratedExtension {
	if len(existing) == 0 {
		return codeExts
	}
	if len(codeExts) == 0 {
		return existing
	}
	// Start with codeExts (they take precedence), then append unique entries from existing.
	seen := make(map[string]struct{}, len(codeExts))
	for _, ext := range codeExts {
		seen[ext.Filename] = struct{}{}
	}
	merged := make([]GeneratedExtension, len(codeExts), len(codeExts)+len(existing))
	copy(merged, codeExts)
	for _, ext := range existing {
		if _, ok := seen[ext.Filename]; !ok {
			merged = append(merged, ext)
			seen[ext.Filename] = struct{}{}
		}
	}
	return merged
}

// mergeMultiBlockSourceAnalysis tries to parse multiple JSON fenced blocks and merge
// their http_records into a single SourceAnalysisResult. This handles the case where
// agents output multiple separate JSON blocks (e.g., SAST review with Task 1/2/3).
func mergeMultiBlockSourceAnalysis(raw string) *SourceAnalysisResult {
	blocks := extractAllJSONFromFencedBlocks(raw)
	if len(blocks) == 0 {
		return nil
	}

	merged := &SourceAnalysisResult{}
	anyParsed := false

	for _, block := range blocks {
		// Try as SourceAnalysisResult
		var result SourceAnalysisResult
		if err := json.Unmarshal([]byte(block), &result); err == nil {
			if len(result.HTTPRecords) > 0 {
				merged.HTTPRecords = append(merged.HTTPRecords, result.HTTPRecords...)
				anyParsed = true
			}
			if result.SessionConfig != nil && merged.SessionConfig == nil {
				merged.SessionConfig = result.SessionConfig
			}
			if len(result.Extensions) > 0 {
				merged.Extensions = append(merged.Extensions, result.Extensions...)
			}
		} else {
			// Array-of-records fallback: block may be a bare JSON array of HTTP records
			var records []AgentHTTPRecord
			if arrErr := json.Unmarshal([]byte(block), &records); arrErr == nil && len(records) > 0 {
				merged.HTTPRecords = append(merged.HTTPRecords, records...)
				anyParsed = true
			}
		}
	}

	if !anyParsed {
		return nil
	}
	return merged
}

// extractAllJSONFromFencedBlocks extracts valid JSON content from ALL ```json fenced
// code blocks (not just the first). Returns all parseable JSON strings.
func extractAllJSONFromFencedBlocks(raw string) []string {
	var results []string
	lines := strings.Split(raw, "\n")
	for i := 0; i < len(lines); i++ {
		trimmed := strings.TrimSpace(lines[i])

		if !strings.HasPrefix(trimmed, "```json") {
			continue
		}
		rest := strings.TrimPrefix(trimmed, "```json")
		if rest != "" && rest[0] != ' ' && rest[0] != '\t' {
			continue
		}

		var content strings.Builder
		i++
		for i < len(lines) {
			if strings.TrimSpace(lines[i]) == "```" {
				break
			}
			if content.Len() > 0 {
				content.WriteByte('\n')
			}
			content.WriteString(lines[i])
			i++
		}

		candidate := strings.TrimSpace(content.String())
		if candidate == "" {
			continue
		}

		if isJSON(candidate) {
			results = append(results, candidate)
		} else if block := findJSONBlock(candidate); block != "" && isJSON(block) {
			results = append(results, block)
		}
	}
	return results
}

// parseSourceAnalysisHybrid parses the hybrid output format where the JSON contains
// http_records and session_config, and extensions are in fenced ```javascript code blocks.
func parseSourceAnalysisHybrid(raw string) (*SourceAnalysisResult, error) {
	// Try extracting JSON from a ```json fenced block first (preferred — unambiguous anchor).
	// Fall back to generic extractJSON() for backward compatibility with raw-JSON output.
	jsonStr, err := extractJSONFromFencedBlock(raw)
	if err != nil {
		jsonStr, err = extractJSON(raw)
		if err != nil {
			return nil, fmt.Errorf("no JSON block found: %w", err)
		}
	}

	// Try wrapped format first
	var wrapper sourceAnalysisWrapper
	if err := json.Unmarshal([]byte(jsonStr), &wrapper); err == nil && len(wrapper.SourceAnalysis.HTTPRecords) > 0 {
		return &wrapper.SourceAnalysis, nil
	}

	// Try direct format
	var result SourceAnalysisResult
	if err := json.Unmarshal([]byte(jsonStr), &result); err != nil {
		// Array-of-records fallback: LLM sometimes outputs [...] instead of {"http_records": [...]}
		var records []AgentHTTPRecord
		if arrErr := json.Unmarshal([]byte(jsonStr), &records); arrErr == nil && len(records) > 0 {
			return &SourceAnalysisResult{HTTPRecords: records}, nil
		}
		return nil, fmt.Errorf("failed to parse JSON: %w", err)
	}
	if len(result.HTTPRecords) == 0 {
		return nil, fmt.Errorf("no http_records found in JSON")
	}

	return &result, nil
}

// ResolveModulesFromPlan converts agent-suggested tags and IDs into a deduplicated
// module ID list. Falls back to ["all"] when no modules are resolved.
func ResolveModulesFromPlan(tags []string, ids []string) []string {
	moduleSet := make(map[string]bool)

	if len(tags) > 0 {
		resolved := modules.ResolveModuleTags(tags)
		for _, id := range resolved {
			moduleSet[id] = true
		}
	}

	for _, id := range ids {
		moduleSet[id] = true
	}

	if len(moduleSet) == 0 {
		return []string{"all"}
	}

	result := make([]string, 0, len(moduleSet))
	for id := range moduleSet {
		result = append(result, id)
	}
	return result
}

// WriteExtensionsToTempDir writes generated JavaScript extensions to a temporary
// directory and returns the directory path. Caller is responsible for cleanup.
func WriteExtensionsToTempDir(extensions []GeneratedExtension, prefix string) (string, error) {
	dir, err := os.MkdirTemp("", prefix)
	if err != nil {
		return "", fmt.Errorf("failed to create temp dir: %w", err)
	}

	for i, ext := range extensions {
		filename := sanitizeExtensionFilename(ext.Filename, i)
		path := filepath.Join(dir, filename)
		if writeErr := os.WriteFile(path, []byte(ext.Code), 0644); writeErr != nil {
			zap.L().Warn("Failed to write extension",
				zap.String("filename", ext.Filename),
				zap.Error(writeErr))
			continue
		}
		zap.L().Info("Generated extension",
			zap.String("filename", ext.Filename),
			zap.String("reason", ext.Reason))
	}

	return dir, nil
}
