package agent

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/vigolium/vigolium/pkg/modules"
	"go.uber.org/zap"
)

// PipelinePhase identifies a phase in the multi-phase scanning pipeline.
type PipelinePhase string

const (
	PhaseSourceAnalysis PipelinePhase = "source-analysis"
	PhaseDiscover       PipelinePhase = "discover"
	PhasePlan           PipelinePhase = "plan"
	PhaseScan           PipelinePhase = "scan"
	PhaseTriage         PipelinePhase = "triage"
	PhaseRescan         PipelinePhase = "rescan"
	PhaseReport         PipelinePhase = "report"
)

// AllPipelinePhases returns the ordered list of pipeline phases.
func AllPipelinePhases() []PipelinePhase {
	return []PipelinePhase{
		PhaseSourceAnalysis, PhaseDiscover, PhasePlan, PhaseScan,
		PhaseTriage, PhaseRescan, PhaseReport,
	}
}

// AttackPlan is the structured output from the plan agent checkpoint (phase 2).
// The agent analyzes discovery results and produces a scanning strategy.
type AttackPlan struct {
	ModuleTags []string          `json:"module_tags"`
	ModuleIDs  []string          `json:"module_ids,omitempty"`
	FocusAreas []string          `json:"focus_areas,omitempty"`
	SkipPaths  []string          `json:"skip_paths,omitempty"`
	Endpoints  []PlannedEndpoint `json:"endpoints,omitempty"`
	Notes      string            `json:"notes,omitempty"`
}

// PlannedEndpoint represents a prioritized endpoint in the attack plan.
type PlannedEndpoint struct {
	URL       string   `json:"url"`
	Method    string   `json:"method,omitempty"`
	Priority  string   `json:"priority"` // high, medium, low
	Rationale string   `json:"rationale,omitempty"`
	Tags      []string `json:"tags,omitempty"`
}

// TriageResult is the structured output from the triage agent checkpoint (phase 4).
// The agent reviews findings and decides whether additional scanning is needed.
type TriageResult struct {
	Confirmed      []TriagedFinding `json:"confirmed"`
	FalsePositives []TriagedFinding `json:"false_positives"`
	FollowUps      []FollowUpScan   `json:"follow_up_scans,omitempty"`
	Verdict        string           `json:"verdict"` // "done" or "rescan"
	Notes          string           `json:"notes,omitempty"`
}

// TriagedFinding is a finding that has been reviewed by the triage agent.
type TriagedFinding struct {
	Title    string `json:"title"`
	ModuleID string `json:"module_id,omitempty"`
	URL      string `json:"url,omitempty"`
	Reason   string `json:"reason,omitempty"`
}

// FollowUpScan describes a targeted rescan recommended by the triage agent.
type FollowUpScan struct {
	URL        string   `json:"url"`
	Method     string   `json:"method,omitempty"`
	ModuleTags []string `json:"module_tags,omitempty"`
	ModuleIDs  []string `json:"module_ids,omitempty"`
	Rationale  string   `json:"rationale,omitempty"`
}

// SourceAnalysisResult is the structured output from the source analysis phase (phase 0).
// The agent explores source code and extracts routes, session config, and custom extensions.
type SourceAnalysisResult struct {
	HTTPRecords   []AgentHTTPRecord    `json:"http_records"`
	SessionConfig *AgentSessionConfig  `json:"session_config,omitempty"`
	Extensions    []GeneratedExtension `json:"extensions,omitempty"`
}

// AgentSessionConfig holds session definitions generated by the source analysis agent.
type AgentSessionConfig struct {
	Sessions []AgentSessionEntry `json:"sessions"`
}

// AgentSessionEntry represents a single session identity for authenticated scanning.
type AgentSessionEntry struct {
	Name    string            `json:"name"`
	Role    string            `json:"role"`               // "primary" or "compare"
	Headers map[string]string `json:"headers,omitempty"`   // static auth headers
	Login   *AgentLoginFlow   `json:"login,omitempty"`     // login-based auth
}

// AgentLoginFlow defines a login flow discovered from source code analysis.
type AgentLoginFlow struct {
	URL         string             `json:"url"`
	Method      string             `json:"method"`
	ContentType string             `json:"content_type,omitempty"`
	Body        string             `json:"body,omitempty"`
	Extract     []AgentExtractRule `json:"extract"`
}

// AgentExtractRule defines how to extract an auth token from a login response.
type AgentExtractRule struct {
	Source  string `json:"source"`            // "cookie", "json", "header"
	Name    string `json:"name,omitempty"`    // cookie name or header name
	Path    string `json:"path,omitempty"`    // JSONPath for json source
	ApplyAs string `json:"apply_as,omitempty"` // e.g. "Authorization: Bearer {value}"
}

// GeneratedExtension represents a JavaScript extension generated by the agent.
type GeneratedExtension struct {
	Filename string `json:"filename"`
	Code     string `json:"code"`
	Reason   string `json:"reason"`
}

// SwarmPlan is the structured output from the master agent in agent swarm mode.
// The agent analyzes the target request, selects modules, and generates custom extensions.
type SwarmPlan struct {
	ModuleTags []string             `json:"module_tags"`
	ModuleIDs  []string             `json:"module_ids,omitempty"`
	Extensions []GeneratedExtension `json:"extensions,omitempty"`
	FocusAreas []string             `json:"focus_areas,omitempty"`
	Notes      string               `json:"notes,omitempty"`
}

// SwarmResult holds the outcome of an agent swarm run.
type SwarmResult struct {
	SwarmPlan      *SwarmPlan      `json:"swarm_plan,omitempty"`
	TriageResults  []*TriageResult `json:"triage_results,omitempty"`
	TotalFindings  int             `json:"total_findings"`
	TotalRecords   int             `json:"total_records"`
	SeverityCounts map[string]int  `json:"severity_counts,omitempty"` // critical, high, medium, low, info
	Confirmed      int             `json:"confirmed"`
	FalsePositives int             `json:"false_positives"`
	Iterations     int             `json:"iterations"`
	Duration       time.Duration   `json:"duration"`
	AgentRunUUID   string          `json:"agent_run_uuid"`
	SessionID      string          `json:"session_id,omitempty"` // ACP session ID for resume
}

// swarmPlanWrapper wraps SwarmPlan for JSON parsing flexibility.
type swarmPlanWrapper struct {
	Plan SwarmPlan `json:"swarm_plan"`
}

// ParseSwarmPlan extracts a SwarmPlan from raw agent output.
// It supports two formats:
//  1. Legacy: a single JSON object containing all fields including extensions[].code
//  2. Hybrid: a single-line JSON plan (module_tags, module_ids, focus_areas, notes)
//     followed by fenced ```javascript code blocks for extensions. Each extension
//     is preceded by a heading like "#### filename.js" and optionally "Reason: ...".
func ParseSwarmPlan(raw string) (*SwarmPlan, error) {
	// Try hybrid format first: JSONL plan line + fenced code blocks for extensions
	if plan, err := parseSwarmPlanHybrid(raw); err == nil && len(plan.ModuleTags) > 0 {
		return plan, nil
	}

	// Fall back to legacy all-in-one JSON format
	jsonStr, err := extractJSON(raw)
	if err != nil {
		return nil, fmt.Errorf("failed to extract JSON from agent output: %w", err)
	}

	// Try wrapped format: {"swarm_plan": {...}}
	var wrapper swarmPlanWrapper
	if err := json.Unmarshal([]byte(jsonStr), &wrapper); err == nil && len(wrapper.Plan.ModuleTags) > 0 {
		return &wrapper.Plan, nil
	}

	// Try direct format: {...}
	var plan SwarmPlan
	if err := json.Unmarshal([]byte(jsonStr), &plan); err == nil && len(plan.ModuleTags) > 0 {
		return &plan, nil
	}

	return nil, fmt.Errorf("failed to parse swarm plan from JSON: invalid structure (expected module_tags)")
}

// parseSwarmPlanHybrid parses the hybrid output format where the plan JSON is a
// single line and extensions are in fenced ```javascript code blocks.
func parseSwarmPlanHybrid(raw string) (*SwarmPlan, error) {
	lines := strings.Split(raw, "\n")

	// Step 1: Find and parse the plan JSON line — first line containing {"module_tags":
	var plan SwarmPlan
	planFound := false
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line == "" || !strings.Contains(line, "\"module_tags\"") {
			continue
		}
		if json.Unmarshal([]byte(line), &plan) == nil && len(plan.ModuleTags) > 0 {
			planFound = true
			break
		}
		// Also try extracting JSON from this line (in case of surrounding text)
		if extracted := findJSONBlock(line); extracted != "" {
			if json.Unmarshal([]byte(extracted), &plan) == nil && len(plan.ModuleTags) > 0 {
				planFound = true
				break
			}
		}
	}

	if !planFound {
		return nil, fmt.Errorf("no plan JSON line found")
	}

	// Step 2: Extract fenced JavaScript code blocks as extensions
	plan.Extensions = extractCodeBlockExtensions(raw)

	return &plan, nil
}

// extractCodeBlockExtensions extracts GeneratedExtension entries from fenced
// ```javascript code blocks in the raw output. It looks for heading patterns
// like "#### filename.js" or "### filename.js" before each block, and
// "Reason: ..." lines for the reason field.
func extractCodeBlockExtensions(raw string) []GeneratedExtension {
	var extensions []GeneratedExtension
	lines := strings.Split(raw, "\n")

	for i := 0; i < len(lines); i++ {
		trimmed := strings.TrimSpace(lines[i])

		// Look for opening fence: ```javascript or ```js
		if !isJSFenceOpen(trimmed) {
			continue
		}

		fenceLineIdx := i

		// Collect code until closing ```
		var code strings.Builder
		i++
		for i < len(lines) {
			if strings.TrimSpace(lines[i]) == "```" {
				break
			}
			if code.Len() > 0 {
				code.WriteByte('\n')
			}
			code.WriteString(lines[i])
			i++
		}

		codeStr := code.String()
		if codeStr == "" {
			continue
		}

		// Extract filename from a preceding heading (#### filename.js / ### filename.js)
		// and reason from a "Reason: ..." line. Scan backwards from the fence line.
		filename, reason := extractExtensionMeta(lines, fenceLineIdx)

		// If no heading filename, try to extract from module id in the code
		if filename == "" {
			filename = extractFilenameFromCode(codeStr)
		}

		extensions = append(extensions, GeneratedExtension{
			Filename: filename,
			Code:     codeStr,
			Reason:   reason,
		})
	}

	return extensions
}

// isJSFenceOpen returns true if the line opens a JavaScript code fence.
func isJSFenceOpen(line string) bool {
	if strings.HasPrefix(line, "```javascript") {
		return true
	}
	// Match ```js but not ```json
	if strings.HasPrefix(line, "```js") && !strings.HasPrefix(line, "```json") {
		return true
	}
	return false
}

// extractExtensionMeta scans lines backwards from fenceIdx to find a heading
// containing a .js filename and an optional "Reason:" line.
func extractExtensionMeta(lines []string, fenceIdx int) (filename, reason string) {
	// Scan up to 5 lines backwards looking for metadata
	start := fenceIdx - 5
	if start < 0 {
		start = 0
	}
	for j := fenceIdx; j >= start; j-- {
		line := strings.TrimSpace(lines[j])

		// Heading with filename: "#### custom-check.js" or "### custom-check.js"
		if filename == "" && strings.HasPrefix(line, "#") {
			// Strip leading # characters and whitespace
			name := strings.TrimLeft(line, "# ")
			if strings.HasSuffix(name, ".js") {
				filename = name
			}
		}

		// Reason line
		if reason == "" && strings.HasPrefix(line, "Reason:") {
			reason = strings.TrimSpace(strings.TrimPrefix(line, "Reason:"))
		}
	}
	return filename, reason
}

// extractFilenameFromCode tries to extract a filename from the module id in JS code.
// It looks for patterns like id: "custom-something" and converts to custom-something.js.
func extractFilenameFromCode(code string) string {
	// Look for id: "..." or id: '...'
	for _, pattern := range []string{`id: "`, `id: '`, `id:"`, `id:'`} {
		idx := strings.Index(code, pattern)
		if idx < 0 {
			continue
		}
		start := idx + len(pattern)
		quote := code[start-1] // matching quote character
		end := strings.IndexByte(code[start:], quote)
		if end > 0 {
			return code[start:start+end] + ".js"
		}
	}
	return "extension.js"
}

// SourceAnalysisConfig configures a source analysis run. Used by both pipeline and swarm.
type SourceAnalysisConfig struct {
	AgentName    string
	TargetURL    string
	SourcePath   string
	Files        []string
	DryRun       bool
	ScanUUID     string
	ProjectUUID  string
	StreamWriter io.Writer
}

// EnsureSessionDir creates the session directory for a given run ID under the specified base directory.
// If baseDir is empty, defaults to ~/.vigolium/agent-sessions/.
// Returns the absolute path to the created directory.
func EnsureSessionDir(baseDir, runID string) (string, error) {
	if baseDir == "" {
		home, err := os.UserHomeDir()
		if err != nil {
			return "", fmt.Errorf("failed to get home dir: %w", err)
		}
		baseDir = filepath.Join(home, ".vigolium", "agent-sessions")
	}
	dir := filepath.Join(baseDir, runID)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return "", fmt.Errorf("failed to create session dir: %w", err)
	}
	return dir, nil
}

// WriteExtensionsToSessionDir writes generated JavaScript extensions to <sessionDir>/extensions/
// and returns the extensions subdirectory path.
func WriteExtensionsToSessionDir(extensions []GeneratedExtension, sessionDir string) (string, error) {
	extDir := filepath.Join(sessionDir, "extensions")
	if err := os.MkdirAll(extDir, 0755); err != nil {
		return "", fmt.Errorf("failed to create extensions dir: %w", err)
	}
	for _, ext := range extensions {
		path := filepath.Join(extDir, ext.Filename)
		if writeErr := os.WriteFile(path, []byte(ext.Code), 0644); writeErr != nil {
			zap.L().Warn("Failed to write extension",
				zap.String("filename", ext.Filename), zap.Error(writeErr))
			continue
		}
		zap.L().Info("Generated extension",
			zap.String("filename", ext.Filename),
			zap.String("reason", ext.Reason),
			zap.String("path", path))
	}
	return extDir, nil
}

// PipelineConfig configures a pipeline run.
type PipelineConfig struct {
	TargetURL       string
	AgentName       string
	Focus           string
	SourcePath      string
	Files           []string
	MaxRescanRounds int
	SkipPhases      map[PipelinePhase]bool
	StartFrom       PipelinePhase
	DryRun          bool
	StreamWriter    io.Writer
	ProjectUUID     string
	ScanUUID        string

	// DiscoverFunc runs the discovery phase (deparos + spidering).
	// It should populate the database with HTTP records.
	DiscoverFunc func(ctx context.Context) error

	// ScanFunc runs the dynamic assessment phase with the given module filters.
	// moduleTags and moduleIDs come from the agent's attack plan.
	ScanFunc func(ctx context.Context, moduleTags []string, moduleIDs []string) error

	// PhaseCallback is called when a pipeline phase starts.
	// Used by the API server to emit SSE phase events and update status.
	PhaseCallback func(phase PipelinePhase)

	// SourceAnalysisCallback is called after Phase 0 completes to allow the caller
	// to process generated extensions and session config (e.g. write to disk).
	SourceAnalysisCallback func(result *SourceAnalysisResult) error
}

// PipelineResult holds the outcome of a full pipeline run.
type PipelineResult struct {
	SourceAnalysis *SourceAnalysisResult `json:"source_analysis,omitempty"`
	Plan           *AttackPlan           `json:"plan,omitempty"`
	TriageResults  []*TriageResult       `json:"triage_results,omitempty"`
	TotalFindings  int                   `json:"total_findings"`
	Confirmed      int                   `json:"confirmed"`
	FalsePositives int                   `json:"false_positives"`
	RescanRounds   int                   `json:"rescan_rounds"`
	PhasesRun      []PipelinePhase       `json:"phases_run"`
	Duration       time.Duration         `json:"duration"`
	SessionID      string                `json:"session_id,omitempty"` // ACP session ID for resume
}

// attackPlanWrapper wraps AttackPlan for JSON parsing flexibility.
type attackPlanWrapper struct {
	Plan AttackPlan `json:"plan"`
}

// triageResultWrapper wraps TriageResult for JSON parsing flexibility.
type triageResultWrapper struct {
	Triage TriageResult `json:"triage"`
}

// sourceAnalysisWrapper wraps SourceAnalysisResult for JSON parsing flexibility.
type sourceAnalysisWrapper struct {
	SourceAnalysis SourceAnalysisResult `json:"source_analysis"`
}

// ParseAttackPlan extracts an AttackPlan from raw agent output.
func ParseAttackPlan(raw string) (*AttackPlan, error) {
	jsonStr, err := extractJSON(raw)
	if err != nil {
		return nil, fmt.Errorf("failed to extract JSON from agent output: %w", err)
	}

	// Try wrapped format: {"plan": {...}}
	var wrapper attackPlanWrapper
	if err := json.Unmarshal([]byte(jsonStr), &wrapper); err == nil && len(wrapper.Plan.ModuleTags) > 0 {
		return &wrapper.Plan, nil
	}

	// Try direct format: {...}
	var plan AttackPlan
	if err := json.Unmarshal([]byte(jsonStr), &plan); err == nil && len(plan.ModuleTags) > 0 {
		return &plan, nil
	}

	return nil, fmt.Errorf("failed to parse attack plan from JSON: invalid structure (expected module_tags)")
}

// ParseTriageResult extracts a TriageResult from raw agent output.
func ParseTriageResult(raw string) (*TriageResult, error) {
	jsonStr, err := extractJSON(raw)
	if err != nil {
		return nil, fmt.Errorf("failed to extract JSON from agent output: %w", err)
	}

	// Try wrapped format: {"triage": {...}}
	var wrapper triageResultWrapper
	if err := json.Unmarshal([]byte(jsonStr), &wrapper); err == nil && wrapper.Triage.Verdict != "" {
		return &wrapper.Triage, nil
	}

	// Try direct format: {...}
	var result TriageResult
	if err := json.Unmarshal([]byte(jsonStr), &result); err == nil && result.Verdict != "" {
		return &result, nil
	}

	return nil, fmt.Errorf("failed to parse triage result from JSON: invalid structure (expected verdict)")
}

// ParseSourceAnalysisResult extracts a SourceAnalysisResult from raw agent output.
func ParseSourceAnalysisResult(raw string) (*SourceAnalysisResult, error) {
	jsonStr, err := extractJSON(raw)
	if err != nil {
		return nil, fmt.Errorf("failed to extract JSON from agent output: %w", err)
	}

	// Try wrapped format: {"source_analysis": {...}}
	var wrapper sourceAnalysisWrapper
	if err := json.Unmarshal([]byte(jsonStr), &wrapper); err == nil && len(wrapper.SourceAnalysis.HTTPRecords) > 0 {
		return &wrapper.SourceAnalysis, nil
	}

	// Try direct format: {...}
	var result SourceAnalysisResult
	if err := json.Unmarshal([]byte(jsonStr), &result); err != nil {
		return nil, fmt.Errorf("failed to parse source analysis result from JSON: %w", err)
	}

	return &result, nil
}

// ResolveModulesFromPlan converts agent-suggested tags and IDs into a deduplicated
// module ID list. Falls back to ["all"] when no modules are resolved.
func ResolveModulesFromPlan(tags []string, ids []string) []string {
	moduleSet := make(map[string]bool)

	if len(tags) > 0 {
		resolved := modules.ResolveModuleTags(tags)
		for _, id := range resolved {
			moduleSet[id] = true
		}
	}

	for _, id := range ids {
		moduleSet[id] = true
	}

	if len(moduleSet) == 0 {
		return []string{"all"}
	}

	result := make([]string, 0, len(moduleSet))
	for id := range moduleSet {
		result = append(result, id)
	}
	return result
}

// WriteExtensionsToTempDir writes generated JavaScript extensions to a temporary
// directory and returns the directory path. Caller is responsible for cleanup.
func WriteExtensionsToTempDir(extensions []GeneratedExtension, prefix string) (string, error) {
	dir, err := os.MkdirTemp("", prefix)
	if err != nil {
		return "", fmt.Errorf("failed to create temp dir: %w", err)
	}

	for _, ext := range extensions {
		path := filepath.Join(dir, ext.Filename)
		if writeErr := os.WriteFile(path, []byte(ext.Code), 0644); writeErr != nil {
			zap.L().Warn("Failed to write extension",
				zap.String("filename", ext.Filename),
				zap.Error(writeErr))
			continue
		}
		zap.L().Info("Generated extension",
			zap.String("filename", ext.Filename),
			zap.String("reason", ext.Reason))
	}

	return dir, nil
}
